### ISSUE TITLE
gphoto2 --get-config exposurecompensation doesn't work with Canon EOS R7

### ISSUE THREAD

**Issue by sinardet** [gphoto/libgphoto2#1014]
Hi everyone,
I'm totaly new and would like to use the same command 
gphoto2 --get-config exposurecompensation , gphoto2 --set-config exposurecompensation doesn't work as well.

But when I try I've got only that below:
Label: Exposure Compensation
Readonly: 0
Type: RADIO
Current: 0
Choice: 0 0
END
I've got all the rest of commands like :gphoto2 --get-config iso or aperture etc, they are working perfectly.
My camera is a Canon EOS R7.
Please let me know what can I do to fix it
 Thanks so much
*******************************************

 gphoto2 --debug --get-config exibitioncompensation
0.000708 main                        (2): ALWAYS INCLUDE THE FOLLOWING LINES WHEN SENDING DEBUG MESSAGES TO THE MAILING LIST:
0.000894 main                        (2): gphoto2 2.5.28
0.000973 main                        (2): gphoto2 has been compiled with the following options:
0.001041 main                        (2):  + gcc (C compiler used)
0.001103 main                        (2):  + popt (mandatory, for handling command-line parameters)
0.001168 main                        (2):  + exif (for displaying EXIF information)
0.001235 main                        (2):  + no cdk (for accessing configuration options)
0.001298 main                        (2):  + no aa (for displaying live previews)
0.001361 main                        (2):  + no jpeg (for displaying live previews in JPEG format)
0.001423 main                        (2):  + no readline (for easy navigation in the shell)
0.001494 main                        (2): libgphoto2 2.5.27
0.001566 main                        (2): libgphoto2 has been compiled with the following options:
0.001637 main                        (2):  + standard camlib set (ax203 canon digigr8 dimagev directory docupen jl2005a jl2005c kodak_dc240 lumix mars pentax ptp2 ricoh_g3 sierra sonix sq905 st2205 topfield tp6801)
0.001704 main                        (2):  + gcc (C compiler used)
0.001842 main                        (2):  + ltdl (for portable loading of camlibs)
0.001906 main                        (2):  + EXIF (for special handling of EXIF files)
0.001977 main                        (2): libgphoto2_port 0.12.0
0.002050 main                        (2): libgphoto2_port has been compiled with the following options:
0.002117 main                        (2):  + iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi
0.002179 main                        (2):  + gcc (C compiler used)
0.002240 main                        (2):  + ltdl (for portable loading of iolibs)
0.002301 main                        (2):  + EXIF (for vusb)
0.002363 main                        (2):  + USB (libusb1, for USB cameras)
0.002423 main                        (2):  + serial (for serial cameras)
0.002484 main                        (2):  + no resmgr (serial port access and locking)
0.002545 main                        (2):  + no ttylock (serial port locking)
0.002607 main                        (2):  + no lockdev (serial port locking)
0.002670 main                        (2): CAMLIBS env var not set, using compile-time default instead
0.002732 main                        (2): IOLIBS env var not set, using compile-time default instead
0.002794 main                        (2): invoked with following arguments:
0.002855 main                        (2):   --debug
0.002915 main                        (2):   --get-config
0.002976 main                        (2):   exibitioncompensation
0.003144 load_settings               (2): Creating gphoto config directory ('/home/kingsley/.gphoto')
0.003374 load_settings               (2): Loading settings from file '/home/kingsley/.gphoto/settings'.
0.003953 main                        (2): The user has not specified both a model and a port. Try to figure them out.
0.004056 gp_port_info_list_load      (2): Using ltdl to load io-drivers from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0'...
0.004546 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/disk'.
0.005680 gp_port_library_list        (2): found fstab fsname proc
0.005856 gp_port_library_list        (2): found fstab fsname PARTUUID=bd461752-01
0.005992 gp_port_library_list        (2): found fstab fsname PARTUUID=bd461752-02
0.006448 gp_port_library_list        (2): found mtab fsname /dev/root
0.006584 gp_port_library_list        (2): found mtab fsname devtmpfs
0.006672 gp_port_library_list        (2): found mtab fsname proc
0.006756 gp_port_library_list        (2): found mtab fsname sysfs
0.006843 gp_port_library_list        (2): found mtab fsname securityfs
0.006928 gp_port_library_list        (2): found mtab fsname tmpfs
0.007060 gp_port_library_list        (2): found mtab fsname devpts
0.007148 gp_port_library_list        (2): found mtab fsname tmpfs
0.007268 gp_port_library_list        (2): found mtab fsname tmpfs
0.007393 gp_port_library_list        (2): found mtab fsname cgroup2
0.007475 gp_port_library_list        (2): found mtab fsname pstore
0.007609 gp_port_library_list        (2): found mtab fsname bpf
0.007727 gp_port_library_list        (2): found mtab fsname systemd-1
0.007810 gp_port_library_list        (2): found mtab fsname mqueue
0.007889 gp_port_library_list        (2): found mtab fsname debugfs
0.008098 gp_port_library_list        (2): found mtab fsname tracefs
0.008221 gp_port_library_list        (2): found mtab fsname sunrpc
0.008362 gp_port_library_list        (2): found mtab fsname fusectl
0.008445 gp_port_library_list        (2): found mtab fsname configfs
0.008583 gp_port_library_list        (2): found mtab fsname /dev/mmcblk0p1
0.008701 gp_port_library_list        (2): found mtab fsname tmpfs
0.008827 gp_port_library_list        (2): found mtab fsname gvfsd-fuse
0.009135 foreach_func                (2): Loaded '' ('^disk:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/disk'.
0.009215 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010178 foreach_func                (2): Loaded 'PTP/IP Connection' ('ptpip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010410 foreach_func                (2): Loaded '' ('^ptpip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010483 foreach_func                (2): Loaded 'IP Connection' ('ip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010552 foreach_func                (2): Loaded '' ('^ip:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/ptpip'.
0.010622 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.011866 foreach_func                (2): Loaded 'Serial Port Device' ('serial:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.011958 foreach_func                (2): Loaded '' ('^serial:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/serial'.
0.012029 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.030561 foreach_func                (2): Loaded '' ('^usb:') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.030691 foreach_func                (2): Loaded 'Universal Serial Bus' ('usb:001,003') from '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usb1'.
0.030760 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usbdiskdirect'.
0.031853 foreach_func                (2): Called for filename '/usr/lib/arm-linux-gnueabihf/libgphoto2_port/0.12.0/usbscsi'.
0.032777 gp_port_info_list_count     (2): Counting entries (9 available)...
0.032919 gp_port_info_list_count     (2): 4 regular entries available.
0.033028 gp_abilities_list_load_dir  (2): Using ltdl to load camera libraries from '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27'...
0.033491 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/ax203'.
0.033573 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/canon'.
0.033635 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/digigr8'.
0.033693 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/dimagev'.
0.033753 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/directory'.
0.033810 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/docupen'.
0.033869 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/jl2005a'.
0.033930 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/jl2005c'.
0.033996 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/kodak_dc240'.
0.034055 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/lumix'.
0.034112 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/mars'.
0.034171 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/pentax'.
0.034230 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/ptp2'.
0.034290 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/ricoh_g3'.
0.034348 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/sierra'.
0.034408 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/sonix'.
0.034469 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/sq905'.
0.034534 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/st2205'.
0.034595 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/topfield'.
0.034655 foreach_func                (2): Found '/usr/lib/arm-linux-gnueabihf/libgphoto2/2.5.27/tp6801'.
0.034755 gp_abilities_list_load_dir  (2): Found 20 camera drivers.
0.237665 gp_port_info_list_count     (2): Counting entries (9 available)...    
0.237800 gp_port_info_list_count     (2): 4 regular entries available.
0.237847 gp_port_new                 (2): Creating new device...
0.237891 gp_port_info_list_get_info  (2): Getting info of entry 0 (9 available)...
0.238415 gp_port_set_settings        (2): Setting settings...
0.238465 gp_port_info_list_get_info  (2): Getting info of entry 1 (9 available)...
0.238791 gp_port_set_settings        (2): Setting settings...
0.238839 gp_port_info_list_get_info  (2): Getting info of entry 2 (9 available)...
0.239249 gp_port_set_timeout         (2): Setting port timeout to 500 milliseconds.
0.239303 gp_port_set_settings        (2): Setting settings...
0.239340 gp_port_info_list_get_info  (2): Getting info of entry 3 (9 available)...
0.249678 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.249792 gp_port_set_settings        (2): Setting settings...
0.249838 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,003, (new int=0, conf=-1, alt=-1) port usb:001,003
0.249873 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.249916 gp_abilities_list_detect_usb(2): Auto-detecting USB cameras...
0.253347 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x29a, subclass, 0xffffffff, protocol 0xffffffff)...
0.255814 gp_libusb1_find_device_by_class_lib(2): Looking for USB device (class 0x6, subclass, 0x1, protocol 0x1)...
0.256024 gp_port_free                (2): Freeing port...
0.256061 gp_port_close               (2): Closing port...
0.257144 gp_camera_set_abilities     (2): Setting abilities ('USB PTP Class Camera')...
0.257215 gp_setting_set              (2): Setting key 'model' to value 'USB PTP Class Camera' (gphoto2)
0.257260 save_settings               (2): Saving 2 setting(s) to file "/home/kingsley/.gphoto/settings"
0.258008 gp_port_info_list_lookup_path(2): Looking for path 'usb:001,017' (9 entries available)...
0.258052 gp_port_info_list_lookup_path(2): Starting regex search for 'usb:001,017'...
0.258089 gp_port_info_list_lookup_path(2): Trying '^disk:'...
0.258209 gp_port_info_list_lookup_path(2): re_match failed (-1)
0.258245 gp_port_info_list_lookup_path(2): Trying '^ptpip:'...
0.258328 gp_port_info_list_lookup_path(2): re_match failed (-1)
0.258364 gp_port_info_list_lookup_path(2): Trying '^ip:'...
0.258442 gp_port_info_list_lookup_path(2): re_match failed (-1)
0.258477 gp_port_info_list_lookup_path(2): Trying '^serial:'...
0.258561 gp_port_info_list_lookup_path(2): re_match failed (-1)
0.258597 gp_port_info_list_lookup_path(2): Trying '^usb:'...
0.258721 gp_port_info_list_get_info  (2): Getting info of entry 4 (10 available)...
0.258764 gp_camera_set_port_info     (2): Setting port info for port 'Generic Port' at 'usb:001,017'...
0.269387 gp_port_set_timeout         (2): Setting port timeout to 5000 milliseconds.
0.269526 gp_port_set_settings        (2): Setting settings...
0.269571 gp_libusb1_update           (2): (old int=0, conf=-1, alt=-1) port usb:001,017, (new int=0, conf=-1, alt=-1) port usb:001,017
0.269607 gp_libusb1_update           (2): lowlevel libusb1 port not yet opened, no need for libusb changes
0.269652 gp_setting_set              (2): Setting key 'port' to value 'usb:001,017' (gphoto2)
0.269696 save_settings               (2): Saving 2 setting(s) to file "/home/kingsley/.gphoto/settings"
0.270489 gp_camera_init              (2): Initializing camera...
0.270610 gp_port_set_error [gphoto2-port.c:1190](0): The supplied vendor or product id (0x0,0x0) is not valid.
*** Error (-52: 'Could not find the requested device on the USB port') ***       

*************************************

**Comment by axxel** [comment]
My guess would be, you set your exposure mode dial to a mode where you don't have that property, like 'M' or 'B'. Please try with e.g. 'P' and see what happens.

**Comment by sinardet** [comment]
Thanks for your answer. As you said of course I know that command :gphoto2 --get-config exposurecompensation doesn't work in Manual mode but is there anychance to get it works because I need absolutely to keep that mode?

**Comment by axxel** [comment]
> is there anychance to get it works because I need absolutely to keep that mode?

I don't understand this sentence. The camera does not support setting exposure compensation in Manual mode. Neither via the camera controls, nor via USB remote.

Can you confirm that setting it works if you set the mode dial to 'P'?

**Comment by sinardet** [comment]
yes it works

**Comment by axxel** [comment]
> yes it works

That is good. So your problem is solved, right?

**Comment by sinardet** [comment]
Not really but I haven't no other choice to use Manual mode for that I need to do, anyway thanks for your help.

**Comment by axxel** [comment]
Well, exposure compensation tells the automatic exposure algorithm of the camera that it should offset its optimal value to make the image darker or brighter. In Manual mode, there is no automatic exposure algorithm at play. Please close this issue.
