### ISSUE TITLE
Silent rules require recent doxygen supporting -q

### ISSUE THREAD

**Issue by ndim** [gphoto/libgphoto2#1046]
**Describe the bug**

Some doxygen versions do not support `-q`, breaking silent rules builds.

**Name the camera**
N/A

**libgphoto2 and gphoto2 version**

git head

**Fix**

Redirect fds 1 and 2 instead?

**Comment by msmeissn** [comment]
i committed a temp fix to disable it

**Comment by ndim** [comment]
According to https://www.doxygen.nl/manual/changelog.html and https://github.com/doxygen/doxygen/commit/3517d8c970ffc575e60cbdde40b041bd404232a2, the doxygen `-q` parameter was first added in the doxygen 1.9.2 release from 2021-08-18 and is equivalent to `QUIET=YES`.
