### ISSUE TITLE
recording video on Sony a5100

### ISSUE THREAD

**Issue by averigo** [gphoto/libgphoto2#106]
Hello,
Thank you very much, gphoto2 --capture-image-and-download --filename = image.jpg works fine on sony a5100 camera. 
Will you add video recording?

Andrei

**Comment by msmeissn** [comment]
On Wed, Nov 02, 2016 at 01:05:39PM -0700, averigo wrote:
> Hello,
> Thank you very much, gphoto2 --capture-image-and-download --filename = image.jpg works fine on sony a5100 camera. 
> Will you add video recording?

There is the movie config option in PC Control mode:

gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0

would record a 10 second movie.

It can however not be retrieved in the PC Control mode currently,
only in the regular access mode.

Ciao, Marcus

**Comment by tiepviet** [comment]
I have a problem. I want to take capture movie on Theta S over USB using gphoto2. Is it possible? I read gphoto2 library but it seems not support "capture movie". Please help me. Sorry for my bad English. Thank you so much.

**Comment by msmeissn** [comment]
it currently is not possible to our knowledge. If the windows software allows it, we can recheck it.
