### ISSUE TITLE
Live view and video recording

### ISSUE THREAD

**Issue by r00li** [gphoto/libgphoto2#11]
Hi!
I am developing an application used for tethered capture. And one of the things that I want to do is support both image and video capture. I have no issues with image capture but I do have some problems with video. The issue seems to be present in gphoto2 and third party libgphoto2 python bindings.

I am using the Canon EOS 5D Mark 2 and gphoto2/libgphoto2 version 2.5.8. If I trigger video recording via the command line with:

```
gphoto2 --set-config viewfinder=1 --set-config movierecordtarget=Card --wait-event=10s --set-config movierecordtarget=None --wait-event=2s
```

then the video gets recorded on to the memory card as I want. 

But If I capture a preview image before that using:

```
gphoto2 --capture-preview
```

then the video will not get captured. Both of the times I will get an output error message saying that property moviecapturetarget was not set. But it will still work in the case I wasn't using preview before that. 

One thing that I've noticed is this: When I have the camera in manual mode I have to enable movie recording in my camera menu (live view function settings -> stills + movie) if I want the movie to be recorded. But when I use the capture preview option that menu option gets reset back to stills only.

Is this a camera specific issue or something that can be solved?

**Comment by msmeissn** [comment]
sorry for not reacting on this issue... i hope it is fixed in some form or the other in newer libgphoto2, please open new ticket if not
