### ISSUE TITLE
Patch: Nikon AW130

### ISSUE THREAD

**Issue by kristapsdz** [gphoto/libgphoto2#116]
This patch gets my Nikon AW130 recognised.  I'm not sure if the BROKEN_CAP still applies; I haven't tried it without.  (Should I?)

[library.c.diff.txt](https://github.com/gphoto/libgphoto2/files/650312/library.c.diff.txt)

**Comment by msmeissn** [comment]
can you please truy it without?

**Comment by kristapsdz** [comment]
Sure---is there a particular set of operations that can bring out whatever behaviour the BROKEN_CAP is meant to solve?

**Comment by msmeissn** [comment]
--capture-image might not work if it is not set ... can you test both SDRAM and CARD capturetargets?

**Comment by kristapsdz** [comment]
The BROKEN_CAP is required: --capture-image fails without it.  I'll look into the capturetargets later!  (This is all from libgphoto2 and gphoto2 in GitHub master on OpenBSD 6.0 using their default package configuration.)
