### ISSUE TITLE
Image doesn't save on SD card using --capture-image on Sony A5000

### ISSUE THREAD

**Issue by HanYangZhao** [gphoto/libgphoto2#117]
Here's the output

➜  ~ gphoto2 --capture-image
New file is in location /capt0000.jpg on the camera
New file is in location /capt0000.arw on the camera
➜  ~ gphoto2 --list-files
There is no file in folder '/'.

I checked with the SD on the computer and there isn't any images there

--capture-image-and-download works

It is because the A5000 doesn't support the feature?
Thanks

**Comment by elijahparker** [comment]
This is a Sony limitation -- saving to the camera's card is disabled while connected via USB

**Comment by msmeissn** [comment]
thats what is also my understanding. it is currently a camera limitation.
(if there is some hidden setting we do not yet this might be the case, but i would assume it is not possible)
