### ISSUE TITLE
Recording video with multiple cameras on Sony Theta S

### ISSUE THREAD

**Issue by tiepviet** [gphoto/libgphoto2#127]
I can `start` recording video mode with gphoto2 on Sony Theta S. But I can't `stop` recording with gphoto2 command. Please help me. Sorry for my problem.

**Comment by msmeissn** [comment]
how do you try to start and stop it?

--set-config movie=0 

should work?

**Comment by tiepviet** [comment]
Thank you for reply my issue. I used below config: 
`--set-config movie=1` : start record (worked true)
`--set-config movie=0` : stop record (not work with transaction error). 
I'm working on Ricoh Theta S. Do I must to modify libgphoto2 to work with this camera?

**Comment by msmeissn** [comment]
there needs to be a fix apparently. a debuglogfile would help, not sure when I find time to try it on my Theta

**Comment by tiepviet** [comment]
@msmeissn Sorry for my delay. Thank your support. This is my log file after I tried to capture with ` gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0`
[capture-movie.txt](https://github.com/gphoto/libgphoto2/files/731529/capture-movie.txt)

**Comment by msmeissn** [comment]
(please test this patch or current git ... it should fix it)

**Comment by tiepviet** [comment]
Thank you very much. Have a nice day!
