### ISSUE TITLE
Bad unpacking of selected Canon AF points

### ISSUE THREAD

**Issue by jbt** [gphoto/libgphoto2#142]
I'm seeing some odd behaviour with some the output for `focusinfo` with EOS 60D for certain AF points.

For example, when the 0th point is selected, the return value includes `select={0,7,}`, and it never seems to include `8` even when it is selected.

I think it's coming from the `i%7` on [this line](https://github.com/gphoto/libgphoto2/blob/78c66ce7e75283c1494e76a0fc67536c3e8ea43b/camlibs/ptp2/ptp-pack.c#L1722) which I'm _fairly_ sure should either be `i&7` or `i%8`.

Happy to make a pull request, although it'll only be a one-character change in any case, and I'm not sure what the testing procedure is.

**Comment by msmeissn** [comment]
you are right, i fixed it in git
