### ISSUE TITLE
iPhone 5 doesn't show the pictures that are on it

### ISSUE THREAD

**Issue by Pointedstick** [gphoto/libgphoto2#147]
I was asked to file an issue here after I originally filed it on GNOME: https://bugzilla.gnome.org/show_bug.cgi?id=779433

The issue is that my iPhone 5 doesn't mount properly with gphoto: it shows up as empty, insteas of displaying all the pictures inside:

$ gvfs-ls gphoto2://[usb:001,008]/
$

There are a ton of attachments with debug info available at https://bugzilla.gnome.org/show_bug.cgi?id=779433

**Comment by Sija** [comment]
Do you use iOS 10.2? If so, there's opened issue #132 for you to checkout :)

**Comment by msmeissn** [comment]
duplicate of issue #132

**Comment by Pointedstick** [comment]
Looks like that's it.
