### ISSUE TITLE
Sony A6000 does not respond to bulb mode given on command line

### ISSUE THREAD

**Issue by justanenduser** [gphoto/libgphoto2#159]
gphoto2 --debug --debug-loglevel=all --debug-logfile=/home/gary/debug --camera="Sony Alpha-A6000 (Control)" --bulb=5 --capture-image --no-keep
Bulb mode enabled (exposure time: 5s).                                         

*** Error ***              
bulb not found in configuration tree.
ERROR: Could not set bulb capture, result -1.
*** Error (-1: 'Unspecified error') ***  

[debug.txt](https://github.com/gphoto/libgphoto2/files/931481/debug.txt)

**Comment by msmeissn** [comment]
there was a small mistake in git, please pull and try again.

**Comment by justanenduser** [comment]
Thank you. It's work fine now.
