### ISSUE TITLE
Fuji X-T2 detected as Nikon DSC D750 

### ISSUE THREAD

**Issue by 22u2** [gphoto/libgphoto2#173]
I have just compiled libgphoto2 and gphoto 2.5.14 to check if I can browse into my X-T2 (Firmware 2.10) but it does not work.

gphoto2 --auto-detect
Nikon DSC D750                 usb:001,001    

[mylog.txt](https://github.com/gphoto/libgphoto2/files/1062406/mylog.txt)

**Comment by msmeissn** [comment]
This means you built without libusb support and it fell back to our internal "virtual" testcamera.

install libusb 1 development headers/libraries and reconfigure / remake

**Comment by 22u2** [comment]
Thanks it works.
Is it reasonable to make it mandatory during the configure step?

**Comment by msmeissn** [comment]
possible, but i can envision scenarios where people might want to build without.

perhaps the other way round, enable the virtual driver only when expclitily enabled
