### ISSUE TITLE
sonix: questionable while loop indentation

### ISSUE THREAD

**Issue by ndim** [gphoto/libgphoto2#177]
`camlibs/sonix/sonix.c` around line 100 contains

    while (status !=2)
        SONIX_READ(port, &status);	
        
        SONIX_READ(port, &status);			

The second `SONIX_READ` is indented as if it belonged into the while loop, but it comes after the while loop.

This is either wrong indentation or wrong logic. But which is it? Either way, it should be fixed.

**Comment by msmeissn** [comment]
yeah i also saw that. I would say the second line is redundant, but without testing this will be hard to find out.
