### ISSUE TITLE
sony slt dual mode wait-event

### ISSUE THREAD

**Issue by msmeissn** [gphoto/libgphoto2#18]
--wait-event-and-download in a dual raw+jpg setting does not work, it leaves one image on camera,
which after some tries fills the memory.

use some logic like in sony_capture

**Comment by falk0069** [comment]
Is this due to the new Sony functions that were just added?  Do you want me to test anything?

**Comment by msmeissn** [comment]
no, its missing things that i have not yet implemented, unrelated to your code

**Comment by gschwim** [comment]
I've seen images get stuck in the camera. With the A7S I have I'm usually able to flush the camera with the following:

    gphoto2 --set-config bulb=0 --wait-event-and-download=5s

This seems to work no matter what mode the camera is in. I usually run it 2x to be sure.

**Comment by msmeissn** [comment]
this should be good now with current git and upcoming 2.5.11 release
