### ISSUE TITLE
Canon M3 "Does not support generic capture"

### ISSUE THREAD

**Issue by samedmonds** [gphoto/libgphoto2#183]
Hi, 
Despite updating to the latest release, it would appear that my Canon M3 is still unsupported. Any ideas as to what the problem might be? 

I'm connecting my M3 to a RaspberryPi and executing gphoto commands via ssh. 

Please see below for a screenshot of the error message when attempting to auto detect. 

<img width="622" alt="screen shot 2017-07-15 at 1 19 44 pm" src="https://user-images.githubusercontent.com/29719179/28236118-c4b6398e-6960-11e7-8e14-82c5088045d4.png">
<img width="540" alt="screen shot 2017-07-15 at 1 20 24 pm" src="https://user-images.githubusercontent.com/29719179/28236119-c4bee070-6960-11e7-8e95-996d7ace1258.png">

**Comment by msmeissn** [comment]
duplicat of https://github.com/gphoto/gphoto2/issues/84

**Comment by Sija** [comment]
@msmeissn typo: duplicat -> duplicate
