### ISSUE TITLE
Make File Issue

### ISSUE THREAD

**Issue by samedmonds** [gphoto/libgphoto2#184]
Hi, 

Am trying to update to 2.5.14 but running into an error when attempting to execute the Makefile. Please see below. 

<img width="927" alt="screen shot 2017-07-16 at 11 14 55 am" src="https://user-images.githubusercontent.com/29719179/28243707-33bd15fc-6a18-11e7-82ff-e1152a1a23d9.png">

**Comment by msmeissn** [comment]
you need to run: 
./configure --prefix=/usr

to generate the Makefile out of Makefile.in 

after that suceeded run make

**Comment by samedmonds** [comment]
Thanks for your help, Marcus. That worked a treat. 

I've since gone onto run `make` and then `sudo make install` but when attempting to --auto-detect my Canon M3, it still does not show up (please see below for output). Any suggestions? 

Sam. 

<img width="457" alt="screen shot 2017-07-16 at 9 10 06 pm" src="https://user-images.githubusercontent.com/29719179/28247017-8ca75076-6a6b-11e7-82fa-243db1f0d53c.png">

**Comment by msmeissn** [comment]
It probably did not overwrite the system libgphoto2 library, you can see with above call that the new binary was found for the gphoto2 tool, but not for the library.

can you see if it installed libraries in /usr/local/lib instead ?

btw, there is an easy script for updating gphoto2, https://github.com/gonzalo/gphoto2-updater  , made by a contributor especiall for rasperry pi

**Comment by samedmonds** [comment]
Thanks again, Marcus! 

I just tried the script you mentioned and it appears to be working!

**Comment by msmeissn** [comment]
thx for reporting back!
