### ISSUE TITLE
gphoto2 16 camera limit

### ISSUE THREAD

**Issue by daboi** [gphoto/libgphoto2#202]
Hi,
I am trying to control 96 Canon cameras with gphoto2 but I cannot get more than 16 cameras displayed on auto-detect. I tried to use different USB ports of my mac but it did not recognize more than 16 cameras. Any suggestions for listing more than 16 cameras on one mac ?

**Comment by msmeissn** [comment]
is "lsusb" showing more than 16 cameras?

This is kind of weird, libgphoto2 has no limitation there as far as I see.

**Comment by daboi** [comment]
When I connect 12 cameras to one port. lsusb shows all 12 cameras. When I connect other 14 cameras alone, lsusb also shows 14 cameras. But when I connect both hubs it shows no camera at all! I use Canon 1200D cameras. What can be the reason for this ? I tried raspbian and macosx sierra, both act same.

**Comment by msmeissn** [comment]
This might be a power related issue, the hubs are probably powered? or some root hub issue.

is there anything error / weird usb related in "dmesg" when plugging in both?

**Comment by daboi** [comment]
Yes it says USB disconnected. and lists several error messages. It might be my usb hubs but there are a lot to change. So currently I will stick with 16 camera per controller.

**Comment by msmeissn** [comment]
not much libgphoto2 can do here, sorry
