### ISSUE TITLE
Can't Trigger-Capture imange Canon Powershot Sx20

### ISSUE THREAD

**Issue by khoa2607** [gphoto/libgphoto2#213]
Hi, I just started to use gphoto2. When I run the command "gphoto2 --trigger-capture". I showed the error
" Error (-6: 'Unsupported operation') "
[logfile.txt](https://github.com/gphoto/libgphoto2/files/1439883/logfile.txt)

I checked other people having the same problem and they posted the logfile.txt here. Hopefully, you can help me to figure out my error. 
Thank you so much for your time and your help!

**Comment by msmeissn** [comment]
the sx20 is not remote controllable, like all canon powershots since the last x years.

so this is not possible sadly.

You can try the  CHDK 3rd party addon , which we support to some degree for remote control.
