### ISSUE TITLE
Can't detect Pentax K5IIs

### ISSUE THREAD

**Issue by kamayok3** [gphoto/libgphoto2#214]
Hi,

I am just wondering is Pentax K5II so much different from K5IIs? How come there is a support for K5II but a no no to K5IIs?

Hope can sort it out soon. 

Regards,
Tom

**Comment by kamayok3** [comment]
Thank you msmeissn for helping me up. K5IIs is in the list now. :)

Regards,
Tom

**Comment by msmeissn** [comment]
thanks for testing and confirming it works :)
