### ISSUE TITLE
i need sony SLR ptp Protocol document  ，but i dont know how to get it

### ISSUE THREAD

**Issue by xiaocainiaooo** [gphoto/libgphoto2#225]
My English is low. I want to get sony SLR ptp Protocol document  to develop a android app to save the problem that read picture from SLR  by android OTG,not effect common shot.
   if you can give it to me . please email to wcswsy@foxmail.com .if it need Business agreement.Please tell me the way.
If you will undertake the affair, I shall be very grateful.

**Comment by msmeissn** [comment]
we do not have such a document. our knowledge about Sony Alpha is largely reverse engineered and trial and error, but neither from a document, nor documented except in source code.
