### ISSUE TITLE
 Canon EOS M6 support

### ISSUE THREAD

**Issue by slepkaviba** [gphoto/libgphoto2#235]
Hi,

I see that M6 is not in the list - is there any support plan for that model (I guess and hope its fairy similar to M5).

Br,
S.

**Comment by msmeissn** [comment]
it probabluy will just work... do you have the USB ids? can you test?

**Comment by slepkaviba** [comment]
usb:001,011

I can set up some Ubuntu VM and check if it helps.

**Comment by msmeissn** [comment]
this is jus the bus location. can you run:

lsusb    

and quote the line of the camera?

**Comment by slepkaviba** [comment]
God, was surprised it simply matches my ports...

ID 04a9:32c5

Here you go.

**Comment by msmeissn** [comment]
If you have a gphoto2 installed, just try 
gphoto2 --capture-image
for starters :)

**Comment by slepkaviba** [comment]
Ok, that one seemed to do the trick. Picture was taken.

**Comment by msmeissn** [comment]
thx for the feedback, considering working similar to eos m5 / m10
