### ISSUE TITLE
Lags on v2.5.9

### ISSUE THREAD

**Issue by Sija** [gphoto/libgphoto2#24]
Hi!

Version `2.5.9` introduced lag between call to `take_picture` and actual effect.
This didn't happen in previous versions.

Any idea what can be done with it?
We wouldn't like to lock ourselves on `2.5.8` as the last working version...

Tested on `Debian` and `Mac OS` with `Canon 550D`.

**Comment by msmeissn** [comment]
can you get a debug logfile of this lag? --debug --debug-logfile=xx.log

**Comment by msmeissn** [comment]
no reply .,.. if you could send debug, please reopen

**Comment by ratwix** [comment]
Hello, I have the same issue with a 550D as well. Same lag with the last 5.9.1. I have to revert to 2.5.8.
I use libgphoto2 on C++. How can I build a log file ?

Thank.

**Comment by msmeissn** [comment]
i changed the eos capturing to wait for the focusing event. are you using manual focus?

**Comment by ratwix** [comment]
Hello, no I use automatic focus. The workflow looks : focus, when focus done wait 2-3 sec, shoot.

**Comment by msmeissn** [comment]
can you reproduce this somehow with the commandline tool ?  have to try myself too

**Comment by ratwix** [comment]
Unfortunatly my will get back my eos wednesday. I will test it asap.

**Comment by ratwix** [comment]
Just for information, I have the preview mode active (mirror up), maybe it change something, I didn't try  without it.

**Comment by msmeissn** [comment]
We made various improvements to EOS support in the last 2 years, please try a newer libgphoto2 version :)
