### ISSUE TITLE
libgphoto2 tests FTBFS on big endian machines

### ISSUE THREAD

**Issue by awilfox** [gphoto/libgphoto2#244]
`gphoto-m4/gp-byteorder.m4` does not have a definition for `htole64` for big endian CPUs.  Thusly, when the test suite is built on a big endian CPU, the following error is encountered:

```
test-endian.o: In function `main':
/usr/src/aports/main/libgphoto2/src/libgphoto2-2.5.16/tests/test-endian.c:58: undefined reference to `htole64'
collect2: error: ld returned 1 exit status
```

**Comment by msmeissn** [comment]
This is a bit weird, it works for me on s390x 64bit... but there was a missing htole64, which I have now added. Thanks for the report!
