### ISSUE TITLE
canon 20D no widget "capture target" 

### ISSUE THREAD

**Issue by paskeyes** [gphoto/libgphoto2#268]
Hello,

I am able to test the canon 20D with kstars/ekos/indi instead of the 5D3 (for which i have issues with gphoto2, already posted)

I noted a little difference : when i shoot, the photo stays on the CF memory card of the camera even after having uploading them. After a brief talk with Jasem on ekos, it seems there is no widget for "capture target" defined on the 20D.

Is it due to some limitation ? or can it be added also like on other camera ? (As i don't have a big mem. card, i will be short during the night if the photo stays on the camera)

Thanks in advance for your info/help,
Best regards,

Pask

**Comment by paskeyes** [comment]
oh ... and  as i am testing that camera : 
How can i shoot >30sec exposure ? 
The bulb mode of the camera is reached by selecting time exposure on manual mode, going to 30sec, then next value is "bulb"
When i send a command for an exposure >30s through gphoto, the camera stops always at 30sec, never above (even the LCD screen shows "30sec exposure" progress)

Is there a way to do >30s ?

Thanks again !

**Comment by msmeissn** [comment]
The 20D is quite old it was using a different driver and methods. It might be possible, but I have not looked at this driver yet.

I do not see bulb handling implemented in the driver either for the EOS 20D, so i dont think there is this possibiolity right now.

**Comment by paskeyes** [comment]
Thank you Marcus for your feedback,
Well, i don't think this camera worth any investment for dev. so i believe i will just give it back. 

Thanks,
Pask

**Comment by msmeissn** [comment]
ok!
