### ISSUE TITLE
USB IDs for Fujifilm X30 and X70

### ISSUE THREAD

**Issue by gscholz** [gphoto/libgphoto2#281]
Dear developers,
here are the USB IDs for respective Fujifilm cameras to add at  "camlibs/ptp2/library.c"

{"Fuji:Fujifilm X70",                  0x04cb, 0x02ba, 0},

{"Fuji:Fujifilm X30",                   0x04cb, 0x02c1, 0},

Regards
Guido

**Comment by msmeissn** [comment]
thx!
