### ISSUE TITLE
Where is "--config" on gphoto2 & libgphoto2 2.5.9?

### ISSUE THREAD

**Issue by ChunshengZhao** [gphoto/libgphoto2#29]
I build gphoto2 and libgphoto2 2.5.9, but not found "--config"? "--list-config" working fine. 
What steps have I forgotten?

BTW： 
{"Nikon:Coolpix 4100 (PTP mode)", 0x04b0,0x012d, PTP_CAP|0}
fix it:
{"Nikon:Coolpix 4100 (PTP mode)", 0x04b0,0x012d, PTP_CAP|PTP_NO_CAPTURE_COMPLETE}

**Comment by msmeissn** [comment]
The --config option for gphoto2 requires the CDK development headers and libs to build,
install cdk-dev or cdk-devel before running configure.

**Comment by ChunshengZhao** [comment]
Thx.
