### ISSUE TITLE
Compile dependencies missing in INSTALL file / no error while configuring (Ubuntu 18.04)

### ISSUE THREAD

**Issue by derMart** [gphoto/libgphoto2#290]
The INSTALL file lists these packages as dependency:
`automake, autoconf, autopoint, gettext, libtool`

after installing those and running
`autoreconf --install --symlink`
I get a lot of warnings:
`configure.ac:576: warning: PKG_PROG_PKG_CONFIG is m4_require'd but not m4_defun'd`
and ./configure command does not generate a makefile and exits without any warning or error.
After installing the package
`pkgconf`
everything works as expected without the warnings.
It would be nice if
a) The autoreconf or configure command should stop with an error if pkgconf is not installed
b) The package pkgconf should be added to the dependency list in the INSTALL file

best

**Comment by msmeissn** [comment]
i have added pkgconfig to INSTALL as suggested
