### ISSUE TITLE
Sony DSC (wx1) Tethered Shooting Support (?)

### ISSUE THREAD

**Issue by PictureHunter** [gphoto/libgphoto2#3]
hallo,

where can i get "Tethered Shooting" supporting drivers for the "Sony DSC" modells especially the wx1 ?

Thx

**Comment by msmeissn** [comment]
This is the libgphoto2 library, a unix based library. As far as I know the compact sonys do not allow remote tether. The Sony A* series do and are supported by libgphoto2.
