### ISSUE TITLE
Canon 60D: Canon EOS Full-Press failed (0x2019: PTP Device Busy)

### ISSUE THREAD

**Issue by tobiasBora** [gphoto/libgphoto2#304]
Hello,

First thank you for this great software. However, I get the following error when I try to take a picture (while darktable can take the picture without any trouble): `Canon EOS Full-Press failed (0x2019: PTP Device Busy)`. You can find enclosed the log file as well as the output I get on stdin: [my-logfile.txt](https://github.com/gphoto/libgphoto2/files/2343663/my-logfile.txt)

Thank you!

NB: I tried with the debian unstable version as well as with the nix version.

-- EDIT --
Fun fact: if I'm in manual mode, I've the error above, but in Video mode, it takes the picture with success! I looks like if the viewfinder is enabled it works, else it fails...

-- EDIT 2 --
Indeed, I understand now why only viewfinder worked. For some reasons it didn't manage to focus on my wall (I guess it was too uniform), and that's why it refuses to take the picture. Sorry for that, I'm closing this issue.

-- EDIT 3 --
It is not really linked, but for people that want to be able to separately focus and take the picture, you should either turn your focus mode to `AI Focus AF` (I think `AI Servo AF` should also work) or move the focus button to another button by setting `C.Fn. IV-1 AF and metering buttons` to 1, and then to turn on focus you can use (at least on Canon 60D) `set-config autofocusdrive=1` (set it to 0 to stop focusing, I made all of these commands into a `gphoto2 --shell`), and `capture-image` to take the picture. Or if you want "manual focus", go in liveview `set-config viewfinder=1`, use `capture-preview` to take a preview picture, and use `set-config  manualfocusdrive=<number between 0 and 6>` to move the zoom step by step. Hope it can help ;-)

**Comment by msmeissn** [comment]
thanks for the updates, i did not get around to looking at it :/ 
interesting it reports device busy , need to check if we can do this a bit differently

**Comment by meron1122** [comment]
@msmeissn I confirm this issue too on eos 4000D
