### ISSUE TITLE
How to set ZOOM?

### ISSUE THREAD

**Issue by Patrickyp** [gphoto/libgphoto2#326]
Hi!
I have a canon powershot A620 which I'm able to set the zoom using the cmd gphoto tool with the following command:
`gphoto2 --set-config zoom=7`

I would like to do this using C programmatically can anyone point me to which example code or function I need to look at?  Thanks.

**Comment by msmeissn** [comment]
look in libgphoto2/examples/focus.c for instance, camera_manual_focus   changes the camera focus in a GP_WIDGET_RANGE mode

**Comment by Patrickyp** [comment]
I am trying to run some of the examples but I'm getting a could not detect any camera error for example `./sample-owner` gives me.  This is with gphoto cmdline program perfectly seeing the camera and capturing.

> *** Contexterror ****
> Could not detect any camera
> No camera auto detected.

Also trying to recompile some examples gives me an error.  gcc

**Comment by Patrickyp** [comment]
nevermind I think I got it.  You guys should update the comment for correct gcc command for C newbies like me can figure out how to recompile the code easier
