### ISSUE TITLE
Add support Canon EOS 800D

### ISSUE THREAD

**Issue by Anastasy888** [gphoto/libgphoto2#338]

**Comment by msmeissn** [comment]
can you provide the usb ids for us to add?

in general it shoulod just work even withut the ids added

**Comment by msmeissn** [comment]
gphoto2 --auto-detect   should already show Rebel 7Ti, (the US name of the EOS 800D).
so just use this...

I added the 800D alias for future releases

**Comment by Anastasy888** [comment]
Thanks. I've changed the name of the camera and now it works.
