### ISSUE TITLE
copying images from a camera gives -1: 'Unspecified error', second attempt succeeds (regression from 2.5.7)

### ISSUE THREAD

**Issue by kparal** [gphoto/libgphoto2#34]
When I try to copy pictures from my camera, I get `error getting file: -1: unspecified error` in Nautilus for every single picture. The pictures *are* copied over, but it shows this error for every single one of them. Using gphoto2, it looks like this:
```
$ gphoto2 --debug --debug-logfile=gphoto2-debug.log --get-file 2 
                                                                               
*** Error ***              
PTP Invalid Object Handle
*** Error (-1: 'Unspecified error') ***       
```
Again, second attempt for the same image succeeds every time (even after disconnecting and reconnecting the device, that image can be copied without issues).

I have reported the issues initially against gvfs, please see the full bug report here:
https://bugzilla.gnome.org/show_bug.cgi?id=760162

There is gphoto2 debug log attached here:
https://bugzilla.gnome.org/attachment.cgi?id=318316

Copying works correctly with libgphoto2-2.5.7-4.fc23.x86_64, but is broken with libgphoto2-2.5.8-1.fc23.x86_64 (Fedora 23).

Thanks for looking into this.

**Comment by msmeissn** [comment]
the setobjectarchive opcode failed (even though it should not). 

i fixed this only half way in 2.5.9, now it is fully fixed for 2.5.10

**Comment by kparal** [comment]
Awesome, thank you. If you could publish a 2.5.10 release soon, I'd then ask my distribution to package it and send us an update. Thanks.

**Comment by kparal** [comment]
Hello, any chance to cut a new release soon? Thanks a lot.

**Comment by msmeissn** [comment]
Given t he amount of testing I want to do before each release I cannot say how long this will take.

**Comment by msmeissn** [comment]
(but I have planned to do a release soon.)

**Comment by kparal** [comment]
:+1: ;) No rush, just asking, this bug does not break functionality too much, it's just annoying.
