### ISSUE TITLE
Sony DSC-WX350 is going to shut down after gphoto2 command execution

### ISSUE THREAD

**Issue by fujii** [gphoto/libgphoto2#355]
Sony DSC-WX350 is going to shut down after `gphoto2` command execution, for example `gphoto2 --list-files`.

I'm testing with libgphoto2-2.5.22.tar.bz2 and gphoto2-2.5.20.tar.bz2.

I uploaded the log of `dmesg` and `gphoto2 --list-files --debug`.
https://gist.github.com/fujii/dcc3cf108a4fca98f21493bc80f32702

* https://github.com/gphoto/libgphoto2/issues/323 and https://github.com/gphoto/libgphoto2/issues/65 seem  similar issues.
* gtkam seems working fine
* If gvfs-gphoto2-volume-monitor is running background, camera is going to shut down immediately after connected.

**Comment by msmeissn** [comment]
I removed a command call on close which caused it to swirtch to charger mode.... Need to reverse engineer the exact arguments there.
