### ISSUE TITLE
gp_list_get_name returns generic class for non-Canon cameras

### ISSUE THREAD

**Issue by knro** [gphoto/libgphoto2#359]
We use `gp_list_get_name` function to get the camera name in INDI driver. For Canon cameras, we get the camera name like "Canon 600D". For non-Canon cameras, a generic name is always returned "USB PTP Class Camera" where as the gphoto --summary returns the correct name.

```
Manufacturer: Nikon Corporation
Model: D7500
  Version: V1.01
  Serial Number: 00000000000000000000000009260479
Vendor Extension ID: 0xa (1.0)
Vendor Extension Description: Microsoft.com/DeviceServices: 1.0

Capture Formats: JPEG Undefined Type
Display Formats: JPEG, Undefined Type, Association/Directory, TIFF, DPOF, Script, Apple Quicktime, Unknown(b982)

Device Capabilities:
	File Download, File Deletion, File Upload
	Generic Image Capture, No Open Capture, Nikon Capture 1, Nikon Capture 2, Nikon Capture 3 
```

I checked the GPhoto summary functions and they do not use gp_list_xxx functions.

**Comment by msmeissn** [comment]
not sure what the problem is here, might be old libgphoto2...
