### ISSUE TITLE
Download failing for captures longer that 3-4 

### ISSUE THREAD

**Issue by MaheshRaviVarma** [gphoto/libgphoto2#381]
Camera: Nikon d7000
Platform: RPi 3B
OS: Ubuntu mate 16.04 LTS
libgphoto2 version : latest (*.*.22)

Error: libusb_bulktransfer time-out pipe error (-9)

Let me know if you need more details

**Comment by msmeissn** [comment]
what is 3-4?  MB? pictures?

**Comment by msmeissn** [comment]
no reply ... please reopen if there is more info.
