### ISSUE TITLE
--capture-image-and-download error -6 with EOS M100

### ISSUE THREAD

**Issue by nadre** [gphoto/libgphoto2#384]
Hi there, awesome project!

When running 

`
gphoto2 --port usb: --capture-image-and-download
`

on my Raspy connected to a EOS M100, I'm getting this error:

`
*** Error ***              
Sorry, your camera does not support generic capture
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-6: 'Unsupported operation') *** 
`

Any ideas?

Here's the log:

[my-logfile.txt](https://github.com/gphoto/libgphoto2/files/2928069/my-logfile.txt)

Best, Erdan.

**Comment by xuyao178** [comment]
It's seems your libgphoto2(2.5.12) version too old. Try to upgrade it to newest version.

**Comment by msmeissn** [comment]
yes, the libgphoto2 version needs to be updated for EOS M support.

**Comment by nadre** [comment]
yes, it worked. thanks.

**Comment by Heinnn** [comment]
how to update the libgphoto2?
I tried to download from https://sourceforge.net/projects/gphoto/files/
then 
autoreconf --install --symlink
./configure
make
sudo make install

but when I typed gphoto2 --version, It still be a libgphotos 2.5.12
Anyway to update???

Thanks
