### ISSUE TITLE
support new olympus pen remote capture

### ISSUE THREAD

**Issue by msmeissn** [gphoto/libgphoto2#41]
the olympus e-m5 mark 2 seems to have quite a lot of vendor properties and vendor propcodes, it looks like has vendor capture again

**Comment by msmeissn** [comment]
(check the new SDK ... should bne 15 US$ from the olympus site, if you can find it :/

**Comment by FreddieChopin** [comment]
Is there anything I could do to help you add support for remote control for E-M5 Mark II? (;

**Comment by msmeissn** [comment]
support was meanwhile added in libgphoto2 2.5.19
