### ISSUE TITLE
libgphoto2 can't be updated to last version

### ISSUE THREAD

**Issue by Heinnn** [gphoto/libgphoto2#412]
how to update the libgphoto2?
I tried to download from https://sourceforge.net/projects/gphoto/files/
thenautoreconf --install --symlink
./configure
make
sudo make install
but when I typed gphoto2 --version, It still be a libgphotos 2.5.12
Anyway to update???Thanks

Copyright (c) 2000-2018 Lutz Mueller and others

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

This version of gphoto2 is using the following software versions and options:
gphoto2         2.5.20         gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.12         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking

**Comment by msmeissn** [comment]
you need to pass --prefix=/usr and --libdir=/correctlibrarydirectory here
(the correctlibrary dir ectiroy depends on your distribution)

otherwise the new files will be installed to /usr/local/ and not necessary visible to gpoto2.
