### ISSUE TITLE
Panasonic GH5 and GH4 not support take a movie.

### ISSUE THREAD

**Issue by zouzhongy** [gphoto/libgphoto2#429]
Panasonic GH5 and GH4 not support take a movie.

 We Tried it with this command:
gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0 --wait-event-and-download=2s

GH4 only take a picture.And GH5 report "movie not found in configuration tree."

GH5 devices info:
0.028024 print_debug_deviceinfo      (2): Device info:
0.028030 print_debug_deviceinfo      (2): Manufacturer: Panasonic
0.028032 print_debug_deviceinfo      (2):   Model: DC-GH5S
0.028034 print_debug_deviceinfo      (2):   device version: 1.2
0.028037 print_debug_deviceinfo      (2):   serial number: '000000000000000000XHL1804180011'
0.028039 print_debug_deviceinfo      (2): Vendor extension ID: 0x0000001c
0.028041 print_debug_deviceinfo      (2): Vendor extension version: 100
0.028043 print_debug_deviceinfo      (2): Vendor extension description: (null)
0.028048 print_debug_deviceinfo      (2): Functional Mode: 0x0000
0.028050 print_debug_deviceinfo      (2): PTP Standard Version: 100
0.028052 print_debug_deviceinfo      (2): Supported operations:
0.028057 print_debug_deviceinfo      (2):   0x1001 (Get device info)
0.028060 print_debug_deviceinfo      (2):   0x1002 (Open session)
0.028066 print_debug_deviceinfo      (2):   0x1003 (Close session)
0.028069 print_debug_deviceinfo      (2):   0x1004 (Get storage IDs)
0.028072 print_debug_deviceinfo      (2):   0x1005 (Get storage info)
0.028075 print_debug_deviceinfo      (2):   0x1006 (Get number of objects)
0.028081 print_debug_deviceinfo      (2):   0x1007 (Get object handles)
0.028084 print_debug_deviceinfo      (2):   0x1008 (Get object info)
0.028087 print_debug_deviceinfo      (2):   0x1009 (Get object)
0.028090 print_debug_deviceinfo      (2):   0x100a (Get thumbnail)
0.028095 print_debug_deviceinfo      (2):   0x100b (Delete object)
0.028098 print_debug_deviceinfo      (2):   0x100f (Format storage)
0.028101 print_debug_deviceinfo      (2):   0x1014 (Get device property description)
0.028104 print_debug_deviceinfo      (2):   0x1015 (Get device property value)
0.028110 print_debug_deviceinfo      (2):   0x1016 (Set device property value)
0.028113 print_debug_deviceinfo      (2):   0x101b (Get partial object)
0.028116 print_debug_deviceinfo      (2):   0x9102 (Get secure time response)
0.028119 print_debug_deviceinfo      (2):   0x9103 (Set license response)
0.028125 print_debug_deviceinfo      (2):   0x9104 (Get sync list)
0.028128 print_debug_deviceinfo      (2):   0x9402 (Unknown PTP_OC)
0.028131 print_debug_deviceinfo      (2):   0x9403 (Unknown PTP_OC)
0.028134 print_debug_deviceinfo      (2):   0x9108 (Clean data store)
0.028140 print_debug_deviceinfo      (2):   0x9404 (Unknown PTP_OC)
0.028143 print_debug_deviceinfo      (2):   0x9412 (Unknown PTP_OC)
0.028146 print_debug_deviceinfo      (2):   0x9706 (Unknown PTP_OC)
0.028148 print_debug_deviceinfo      (2): Events Supported:
0.028154 print_debug_deviceinfo      (2):   0x4004 (StoreAdded)
0.028157 print_debug_deviceinfo      (2):   0x4005 (StoreRemoved)
0.028160 print_debug_deviceinfo      (2):   0x4006 (DevicePropChanged)
0.028163 print_debug_deviceinfo      (2):   0x4008 (DeviceInfoChanged)
0.028168 print_debug_deviceinfo      (2):   0x400c (StorageInfoChanged)
0.028171 print_debug_deviceinfo      (2):   0xc108 (Unknown Event)
0.028174 print_debug_deviceinfo      (2):   0xc109 (Unknown Event)
0.028177 print_debug_deviceinfo      (2):   0xc101 (Unknown Event)
0.028180 print_debug_deviceinfo      (2):   0xc102 (Unknown Event)
0.028183 print_debug_deviceinfo      (2):   0xc103 (Unknown Event)
0.028186 print_debug_deviceinfo      (2):   0xc104 (Unknown Event)
0.028189 print_debug_deviceinfo      (2):   0xc106 (Unknown Event)
0.028191 print_debug_deviceinfo      (2):   0xc107 (Unknown Event)
0.028194 print_debug_deviceinfo      (2):   0xc201 (Unknown Event)
0.028197 print_debug_deviceinfo      (2):   0xc202 (Unknown Event)
0.028200 print_debug_deviceinfo      (2):   0xc212 (Unknown Event)
0.028202 print_debug_deviceinfo      (2): Device Properties Supported:
0.028208 print_debug_deviceinfo      (2):   0x5001 (Battery Level)

GH4 deviceinfo:
0.049959 print_debug_deviceinfo      (2): Device info:
0.049968 print_debug_deviceinfo      (2): Manufacturer: Panasonic
0.049974 print_debug_deviceinfo      (2):   Model: DMC-GH4
0.049979 print_debug_deviceinfo      (2):   device version: 2.7
0.049984 print_debug_deviceinfo      (2):   serial number: '0000000000000000001X1404270290'
0.049990 print_debug_deviceinfo      (2): Vendor extension ID: 0x00000006
0.049995 print_debug_deviceinfo      (2): Vendor extension version: 100
0.050221 print_debug_deviceinfo      (2): Vendor extension description: (null)
0.050234 print_debug_deviceinfo      (2): Functional Mode: 0x0000
0.050239 print_debug_deviceinfo      (2): PTP Standard Version: 100
0.050244 print_debug_deviceinfo      (2): Supported operations:
0.050252 print_debug_deviceinfo      (2):   0x1001 (Get device info)
0.050258 print_debug_deviceinfo      (2):   0x1002 (Open session)
0.050264 print_debug_deviceinfo      (2):   0x1003 (Close session)
0.050270 print_debug_deviceinfo      (2):   0x1004 (Get storage IDs)
0.050276 print_debug_deviceinfo      (2):   0x1005 (Get storage info)
0.050282 print_debug_deviceinfo      (2):   0x1006 (Get number of objects)
0.050289 print_debug_deviceinfo      (2):   0x1007 (Get object handles)
0.050294 print_debug_deviceinfo      (2):   0x1008 (Get object info)
0.050403 print_debug_deviceinfo      (2):   0x1009 (Get object)
0.050410 print_debug_deviceinfo      (2):   0x100a (Get thumbnail)
0.050547 print_debug_deviceinfo      (2):   0x100b (Delete object)
0.050562 print_debug_deviceinfo      (2):   0x100e (Initiate capture)
0.050568 print_debug_deviceinfo      (2):   0x101c (Initiate open capture)
0.050574 print_debug_deviceinfo      (2):   0x1018 (Terminate open capture)
0.050585 print_debug_deviceinfo      (2):   0x100f (Format storage)
0.050657 print_debug_deviceinfo      (2):   0x1010 (Reset device)
0.050665 print_debug_deviceinfo      (2):   0x1014 (Get device property description)
0.050671 print_debug_deviceinfo      (2):   0x1015 (Get device property value)
0.050677 print_debug_deviceinfo      (2):   0x1016 (Set device property value)
0.050683 print_debug_deviceinfo      (2):   0x101b (Get partial object)
0.050689 print_debug_deviceinfo      (2):   0x9801 (Get object properties supported)
0.050695 print_debug_deviceinfo      (2):   0x9802 (Get object property description)
0.050701 print_debug_deviceinfo      (2):   0x9803 (Get object property value)
0.050707 print_debug_deviceinfo      (2):   0x9805 (Get object property list)
0.050795 print_debug_deviceinfo      (2): Events Supported:
0.050805 print_debug_deviceinfo      (2):   0x4004 (StoreAdded)
0.050811 print_debug_deviceinfo      (2):   0x4005 (StoreRemoved)
0.050822 print_debug_deviceinfo      (2):   0x4002 (ObjectAdded)
0.050907 print_debug_deviceinfo      (2):   0x400d (CaptureComplete)
0.050930 print_debug_deviceinfo      (2):   0x4006 (DevicePropChanged)
0.050937 print_debug_deviceinfo      (2):   0x4008 (DeviceInfoChanged)
0.050944 print_debug_deviceinfo      (2):   0x4009 (RequestObjectTransfer)
0.050950 print_debug_deviceinfo      (2):   0x400c (StorageInfoChanged)
0.051079 print_debug_deviceinfo      (2): Device Properties Supported:
0.051088 print_debug_deviceinfo      (2):   0xd406 (Session Initiator Info)
0.051094 print_debug_deviceinfo      (2):   0xd407 (Perceived Device Type)
0.051099 print_debug_deviceinfo      (2):   0x5007 (F-Number)
0.051105 print_debug_deviceinfo      (2):   0x500a (Focus Mode)
0.051110 print_debug_deviceinfo      (2):   0x500d (Exposure Time)
0.051116 print_debug_deviceinfo      (2):   0x500e (Exposure Program Mode)
0.051121 print_debug_deviceinfo      (2):   0x500f (Exposure Index (film speed ISO))
0.051209 print_debug_deviceinfo      (2):   0x5013 (Still Capture Mode)
0.051216 print_debug_deviceinfo      (2):   0xd001 (Unknown DPC code)
0.051221 print_debug_deviceinfo      (2):   0xd002 (Unknown DPC code)
0.051227 print_debug_deviceinfo      (2):   0x5001 (Battery Level)

bese on deviceinfo,GH4 GH5 not support take a movie.But we use other software can "start Movie and stop movie".we found it use Ptp opcode "0x940C" PTP_OC_PANASONIC_MoveRecControl.But in libgphoto.not support the opcode.

Could you let GH4 and GH5 support take a movie? 
Thanks a lot.

**Comment by msmeissn** [comment]
sorry it took so long to get to it.

it now is in git, 
gphoto2 --set-config movie=1 --wait-event=20s --set-config movie=0 --wait-event-and-download=5s
