### ISSUE TITLE
Canon EOS M3 supported?

### ISSUE THREAD

**Issue by schousda** [gphoto/libgphoto2#463]
Hello!
[Here](https://github.com/gphoto/libgphoto2/issues/58) i was reading, that Canon EOS M models are supported now.
Is the Canon EOS M3 supported already and also the electronic shutter mode?
I found the camera in the [list of supported camears](http://www.gphoto.org/proj/libgphoto2/support.php), but i specially need to know about the electronic shutter. I don't wanna ruin the mechanical shutter while taking a lot of images.

Thanks.

**Comment by msmeissn** [comment]
M3 should work to some degree. configuration setting is always a bit problematic though, but image capture and preview cpature should work
