### ISSUE TITLE
No exposures longer than 4s with libgphoto2 2.5.23 on Nikon D7100

### ISSUE THREAD

**Issue by hronellenfitsch** [gphoto/libgphoto2#465]
I am unable to take exposures longer than 4s with my Nikon D7100. I set the exposure time
on the camera and run

    gphoto2 --capture-image

If the exposure time is 5s or longer, I get this error:

*** Error ***              
PTP Device Busy
ERROR: Could not capture image.
ERROR: Could not capture.
*** Error (-110: 'I/O in progress') ***       

The debug log is attached:
[my-logfile.txt](https://github.com/gphoto/libgphoto2/files/3990716/my-logfile.txt)

The version of gphoto2 is
gphoto2         2.5.23         gcc, popt(m), exif, cdk, aa, jpeg, readline
libgphoto2      2.5.23         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         iolibs: disk ptpip serial usb1 usbdiskdirect usbscsi, gcc, ltdl, USB, serial without locking

as it comes with Ubuntu 19.10. Everything worked fine in Ubuntu 19.04.

**Comment by msmeissn** [comment]
i have a fix in git (not yet released) that extends the wait to 20 seconds, commit 354b1f73ebcd41200653bf95767b936f44d0c71f

it is weird, i was hoping it does not stay busy this long
