### ISSUE TITLE
Build failure due to out of date camlibs

### ISSUE THREAD

**Issue by knro** [gphoto/libgphoto2#466]
I'm maintaining the libgphoto2 PPA for Ubuntu and recently we've been getting [build failures](https://launchpadlibrarian.net/458620687/buildlog_ubuntu-bionic-amd64.libgphoto2_2.5.23+202001011630~ubuntu18.04.1_BUILDING.txt.gz) on Launchpad.

The error indicates this:
```
List of camlibs in configure.ac is out of date.
Have a developer update it using "make -C camlibs print-camlibs".
```

Can this be done? so we can retry the build and see if it resolves the issue.

**Comment by msmeissn** [comment]
This was due to a conditional build of a new driver (lumix), where I did not correctly checked what happens when libcurl or libxml2 is missing.
Should be fixed in GIT now.
