### ISSUE TITLE
Plese consider tagging conventoion change

### ISSUE THREAD

**Issue by kloczek** [gphoto/libgphoto2#476]
git automatically adds repo name to autogenerated tar balls from git tags. Because current tagginbg convention is `libgphoto2-<version>` thise tar balls are with base directory `libgphoto2-libgphoto2-<version>-release`. Additionally in version all dots are replaced by underscores.

Plese consider change tagging convention to just `<version>` or 'v<version> (git automatically strips leading `v` in version) with dots instead underscores to match version with what is used in release and like it is used in most of the git based projects.

You don't need to distingush in tags that something is release tag because git allows add tag without pointing that it is not release.. This is why in releases tab are two subtabs: Releases and Tags.

**Comment by msmeissn** [comment]
I will see I do that for the next releases

**Comment by msmeissn** [comment]
actually I changed the current release to use v2.5.24
