### ISSUE TITLE
locale and menu values

### ISSUE THREAD

**Issue by GuLinux** [gphoto/libgphoto2#49]
Hi,
I'm not sure if this is related to my camera (canon eos 350d).

When I try to get a widget configuration, with my LC_ALL set to it_IT, I get values translated in my language:

    LC_ALL=it_IT.UTF8 gphoto2 --get-config=imageformat
    Individuata una "Canon:EOS 350D (normal mode)".                                
    Label: Formato immagine
    Type: MENU
    Current: RAW
    Choice: 0 RAW
    Choice: 1 RAW 2
    Choice: 2 JPEG Normale piccola
    Choice: 3 JPEG Fine piccola

But if I try to set it to any of the found values, it just fails:

    LC_ALL=it_IT.UTF8 gphoto2 --set-config imageformat='JPEG Fine larga'
    Individuata una "Canon:EOS 350D (normal mode)".                                
    Impostazione del formato immagine non valida

If I set the value to the appropriate english translation, it works fine:

    LC_ALL=C gphoto2 --set-config imageformat='Large Fine JPEG'
    Detected a 'Canon:EOS 350D (normal mode)'.                                     
    Image format changed

(Note: even if I changed LC_ALL on set-config, it seems completely irrelevant).

I actually noticed this bug not via the gphoto2 app, but trying to change settings via C++ api.
A workaround is to call ````setlocale(LC_ALL, "C"````) just before connecting my camera.

**Comment by msmeissn** [comment]
this was a a problem in the old canon driver, for EOS up to 350D
