### ISSUE TITLE
Pentax 645z

### ISSUE THREAD

**Issue by pironio** [gphoto/libgphoto2#490]
Fill in fields below. If you don't know how, leave it free.

**Ricoh Pentax 645z*

Use the Marketing name.

**2020-04-05 12:20:36.806 system_profiler[27012:4589517] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2020-04-05 12:20:36.807 system_profiler[27012:4589517] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
Bus 020 Device 017: ID 05e3:0616 Genesys Logic, Inc. USB3.0 Hub 
Bus 020 Device 019: ID 25fb:0167 25fb PENTAX 645Z  Serial: 6054510
Bus 020 Device 003: ID 05ac:0262 Apple Inc. Apple Internal Keyboard / Trackpad 
Bus 020 Device 000: ID 0a5c:4500 Broadcom Corp. BRCM20702 Hub 
Bus 020 Device 000: ID 05ac:8289 Apple Inc. Bluetooth USB Host Controller 
Bus 020 Device 018: ID 05e3:0610 Genesys Logic, Inc. USB2.0 Hub 
Bus 000 Device 001: ID 1d6b:LPTH Linux Foundation USB 3.0 Bus **

**camera summary output**
[summary.txt](https://github.com/gphoto/libgphoto2/files/4434613/summary.txt)
**camera configuration output**
[list-all-config.txt](https://github.com/gphoto/libgphoto2/files/4434623/list-all-config.txt)

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
[my-logfile.txt](https://github.com/gphoto/libgphoto2/files/4434628/my-logfile.txt)

 
  gphoto2 --capture-preview
[my-logfile2.txt](https://github.com/gphoto/libgphoto2/files/4434630/my-logfile2.txt)

Please let me know what I can do to help to make this camera work.

Also, this SDK from Pentax might help. https://api.ricoh/products/camera-sdk/

I'm happy to do any grunt work as well just let me know what you need and I will get it done.

Thank you,

Nick

nick@pironio.com

**Comment by msmeissn** [comment]
Sorry for not reacting earlier. The Pentax cameras usually need to be in "USB Srtorage" mode to be controlled, not in PTP mode.
