### ISSUE TITLE
Failed to detect camera with GPhoto2 from Solid information

### ISSUE THREAD

**Issue by mathieumd** [gphoto/libgphoto2#53]
According to the bug [307839](https://bugs.kde.org/show_bug.cgi?id=307839#c20) in Digikam, the _Solid_ component seems to fails somehow when trying to get information from camera through Digikam. The only error message output in the console is:
```
digikam(26035)/digikam (core): Failed to detect camera with GPhoto2 from Solid information
```

I could confirm this bug with both a Nikon D5500 and a Nikon Coolpix P610.

Is there any more information I could provide to help find the root cause?

**Comment by msmeissn** [comment]
it seems to be an issue in either digikam or solid, the kde hardware detection framework.

they only handle "known" cameras for libgphoto2, and not the class based detection.
