### ISSUE TITLE
  Call gp_ camera_ capture_preview The return value of failed: - 6

### ISSUE THREAD

**Issue by xdw-123** [gphoto/libgphoto2#546]
Dear author, I call capture every time_ The return value failed: - 6 appears in preview. My camera model: Song ilce_ 7RM3 。 The language Python is used and the package is Python Gphoto. Looking forward to your reply.

**Comment by xdw-123** [comment]
gphoto2: (gp_camera_capture_preview [gphoto2-camera.c:1096]) 'camera->functions->capture_preview ( camera, file, context)' failed: -6

**Comment by msmeissn** [comment]
i see in the other bug you have libgphoto 2.5.9 ... which is very outdated. please update and try again
