### ISSUE TITLE
Canon PowerShot SX730 HS

### ISSUE THREAD

**Issue by fredj** [gphoto/libgphoto2#561]
Fill in fields below. If you don't know how, leave it free.

**Name of the camera**

Canon PowerShot SX730 HS

*Note:* the camera model is `Canon Digital PowerShot SX730IS` in the output of `gphoto2 --auto-detect`

**USB IDs**
Bus 001 Device 026: ID 04a9:32d6 Canon, Inc. Canon Digital Camera

**camera summary output**
[summary.txt](https://github.com/gphoto/libgphoto2/files/5187314/summary.txt)

**camera configuration output**
[list-all-config.txt](https://github.com/gphoto/libgphoto2/files/5187319/list-all-config.txt)

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
it works

  gphoto2 --capture-preview
it works

**Comment by msmeissn** [comment]
thanks for the report! I adjusted the name
