### ISSUE TITLE
eosremoterelease not availlable for Canon EOS 350D and 450D

### ISSUE THREAD

**Issue by Ultimaboot** [gphoto/libgphoto2#584]
I'am using Stellarmate Ekos en for the camera i use gphoto CCD
When using the Canon EOS 350D or 450D both camera are not responding when using the mirror lock.
The mirror lock is enable on the camera's
Jasem from Stellarmate is saying that on both camera's eosremoterelease is missing.
Can you help me to solve this problem?

With Regards,

Peter

**Comment by msmeissn** [comment]
The 350d used a different protocol. I do not think it has this kind of finegrained shutter controll.

The 450d did not support this kind of shutter control yet, it is only in more recent EOS cameras.

So you will need to get a newer EOS.
