### ISSUE TITLE
get sd card's serial number

### ISSUE THREAD

**Issue by huangmingyou** [gphoto/libgphoto2#594]
Is the gphoto2 --storage-info command can't get the sd card's serial number.

how get the sd card's serial number ?

**Comment by msmeissn** [comment]
What camera is this?

if the storage info does not report it, it is likely not exposed by the camera.

**Comment by huangmingyou** [comment]
canon eos 100D

**Comment by huangmingyou** [comment]
in a android , can use this command get serial number.

root@myhost:~# cat /sys/block/mmcblk1/device/serial
0x45d0a39e

**Comment by msmeissn** [comment]
-> likely not exposed by the camera, firmware limitation
