### ISSUE TITLE
Support for Image Capture and Liveview Canon PowerShot SX210 IS

### ISSUE THREAD

**Issue by hvitoi** [gphoto/libgphoto2#609]
Fill in fields below. If you don't know how, leave it free.

Canon PowerShot SX210 IS

Use the Marketing name.

**USB IDs**
Bus 001 Device 016: ID 04a9:31f6 Canon, Inc. PowerShot SX210 IS

**camera summary output**
[summary.txt](https://github.com/gphoto/libgphoto2/files/5811690/summary.txt)

**camera configuration output**
[list-all-config.txt](https://github.com/gphoto/libgphoto2/files/5811692/list-all-config.txt)

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
`*** Error (-6: 'Unsupported operation') ***` 

  gphoto2 --capture-preview
`*** Error (-6: 'Unsupported operation') ***`

**Comment by msmeissn** [comment]
this cameras is one of the powershot series that does not capture. This is a camera side limitation.

There is the CHDK 3rd party addon which might help with remote controllability, but its less functional and a bit more tricky to use than the regular capture modes in the newer / older powershot series.
