### ISSUE TITLE
Add Canon EOS M200

### ISSUE THREAD

**Issue by yursan9** [gphoto/libgphoto2#614]
Fill in fields below. If you don't know how, leave it free.

**Name of the camera**

Canon EOS M200

**USB IDs**
Bus 001 Device 005: ID 04a9:32ef Canon, Inc. Canon Digital Camera

**camera summary output**
[summary.txt](https://github.com/gphoto/libgphoto2/files/5861517/summary.txt)

**camera configuration output**
[config.txt](https://github.com/gphoto/libgphoto2/files/5861518/config.txt)

**test capture**

test if capture perhaps already works:

  gphoto2 --capture-image-and-download
```
New file is in location /capt0000.cr3 on the camera
Saving file as capt0000.cr3
Deleting file /capt0000.cr3 on the camera
```
  gphoto2 --capture-preview
```
Saving file as capture_preview.jpg
```

**Comment by yursan9** [comment]
That was fast! :+1: Thank you @msmeissn

**Comment by msmeissn** [comment]
No worries :) camera seems well supported already, just the id was missing in the list.
