### ISSUE TITLE
Could not claim usb

### ISSUE THREAD

**Issue by ebolisa** [gphoto/libgphoto2#617]
Hi,

Not sure if this' the right place to expose my issue so, I apologize in advance.

I installed the latest version on a Pi 4 (with no errors) and when I search for my Nikon D70 camera, I get the following response:
**_Nikon DSC D70 (PTP mode)       usb:001,011_**

However, when I try to take a picture I get the following error:
**_An error occurred in the io-library ('Could not claim the USB device')_**

Under FAQ I read up on Why do I get the error message "Could not claim the USB device"? but, I don't quite understand where I should look to sove the problem.

I appreciate any help I can get.
Regards.

Pi4 running OS from USB. No SD installed.

pi@rasp4:~ $ lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 005: ID 04b0:0406 Nikon Corp. DSC D70 (ptp)
Bus 001 Device 003: ID 1bcf:0c31 Sunplus Innovation Technology Inc. SPIF30x Serial-ATA bridge
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by msmeissn** [comment]
gphoto2 is blocked by another tool, on the PI likely gvfs that makes the camera aavailable to Nautilus and other browsers.

try:

gio mount -s gphoto2

and then replugging the camera and see if that helps

**Comment by ebolisa** [comment]
Thank you, made progress.
