### ISSUE TITLE
Show Error When Debug in VS Code Tools

### ISSUE THREAD

**Issue by arnozeng** [gphoto/libgphoto2#635]
**Describe the bug**

i try to use VS code to debug those examples in source code, but vs code shown below error msg. how to fix it? not know more about Makefile's config.
![image](https://user-images.githubusercontent.com/64408767/110567881-279e7500-818d-11eb-9e4c-d63a088d6174.png)

this config of vs code as below:
launch.json:

```
{
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
"version": "0.2.0",
"configurations": [
{
"name": "g++ build",
"type": "cppdbg",
"request": "launch",
"program": "${workspaceFolder}/examples/sample-autodetect",
"args": [],
"stopAtEntry": false,
"cwd": "${workspaceFolder}/examples",
"environment": [],
"externalConsole": false,
"MIMode": "gdb",
"setupCommands": [
{
"description": "",
"text": "-enable-pretty-printing",
"ignoreFailures": true
}
],
"preLaunchTask": "make build",
"miDebuggerPath": "/usr/bin/gdb"
}
]
}
```

tasks.josn
```
{
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
"version": "2.0.0",
"tasks": [
{
"label": "make build",//编译的项目名，build
"type": "shell",
"command": "make",//编译命令
},
{
"label": "clean",
"type": "shell",
"command": "make clean",
}
]
}
```

this example can be run by command successfully, but can't run in vs code tools. some one can help?

**Comment by msmeissn** [comment]
can you try examples/.libs/sample-autodetect

libtool places the binaries in a .libs subdirectory.

**Comment by arnozeng** [comment]
Thanks, just solve the problem from your answer. this exe path should be  "program": "${workspaceFolder}/examples/.libs/sample-autodetect", not "${workspaceFolder}/examples/.libs/sample-autodetect"
