### ISSUE TITLE
does it support sony hx400v

### ISSUE THREAD

**Issue by akashmon598** [gphoto/libgphoto2#644]
**Not able to connect sony hx 400v camera **

I am not able to connect sony hx400v camera.

**sony hx 400v**
Camera name as shown by gphoto2 --auto-detect or USB IDs

**libgphoto2 and gphoto2 version**
output of: gphoto2 --version

**To Reproduce**

When reproducing with the commandline tool, attach debugout using  --debug --debug-logfile=debug.log   if considered useful.

**Comment by msmeissn** [comment]
we list this camera, but so far it looks we support it for downloading images only, no remote control.
