### ISSUE TITLE
nikon z5&&z6&&z50 record  error  0x200f

### ISSUE THREAD

**Issue by stronges** [gphoto/libgphoto2#648]
i need nikon record operate , but have error_code 0x200f ,
this is detail 
![image](https://user-images.githubusercontent.com/33445686/114964797-01fa3f00-9ea2-11eb-8d71-2e168f5769ee.png)

**Comment by msmeissn** [comment]
can you unfold the last OUT transaction, so we can see what property it tries to set there?
also unfold unknown command (last line)

**Comment by stronges** [comment]
![image](https://user-images.githubusercontent.com/33445686/115100465-6b944f00-9f6f-11eb-9f66-cef4c783530c.png)
this  compelete picutre

**Comment by stronges** [comment]
here is  another screenshot of  a successful recording of the product
![image](https://user-images.githubusercontent.com/33445686/115100696-e01bbd80-9f70-11eb-8c67-b45a558dc3f9.png)

**Comment by msmeissn** [comment]
what exact gphoto2 commands do you send?
what version is in use?

output of:
gphoto2 --version

if libgphoto2 is not 2.5.27 , please update libgphoto2 to 2.5.27 as I fixed this movie capture stuff.

**Comment by stronges** [comment]
i want  record video, and want use command  PTP_OC_NIKON_StartMovieRecInCard,  but no implementation ,
I found that I could not enter the application mode during initialization, so not implementation  recording

**Comment by stronges** [comment]
I developed on other platforms without using libphoto library. I just refer to libphoto. May I ask what you have fixed in v2.5.27 and what I need to do on my platform

**Comment by msmeissn** [comment]
The Z series has a new method to switch to application, the PTP_OC_NIKON_ChangeApplicationMode opcode 0x9435 , 1 argument (on = 1, off = 0), no data,   that needs to be used . See the SDK.

**Comment by stronges** [comment]
thanks, i find one of my interrupt  endpoints  is not in runing due to driver reason,  after the repair, recording can proceed normally
