### ISSUE TITLE
interruption to not work for android device

### ISSUE THREAD

**Issue by mat-c** [gphoto/libgphoto2#665]
use gphoto2 2.5.27

download a big file on android device with
* gphoto2 -p num
* use ctrl+c to interrupt it
* the transfert is not canceled.

After investigation, this is because transfer is spited in partial transfer of 1MB : https://github.com/gphoto/libgphoto2/blame/master/camlibs/ptp2/library.c#L8798

And only handle cancel request only for transfer > 1MB https://github.com/gphoto/libgphoto2/blame/master/camlibs/ptp2/usb.c#L466

Also I wonder if there is no performance of using partial transfer instead of a simple getobject

**Comment by msmeissn** [comment]
i changed the condition to >= 1024*1024 which hopefully covers this.

We need to read in smaller blobs, as some camera firmwares crash on larger reads.

The 1MB should be a good match between performance and reliability. (usb will split it up anyway on the bus)
