### ISSUE TITLE
 Downloading capt0000.jpg

### ISSUE THREAD

**Issue by SiuyuenChow** [gphoto/libgphoto2#671]
Camera model: EOS 200DII
When I call gp_camera_wait_for_event, I take the picture and return the following

  Downloading capt0000.jpg / 0...
  Downloading capt0001.jpg / 0...
  Downloading capt0002.jpg / 0...

gphoto2——set-config capturetarget = 1  ---->  like this?  ----->  gp_setting_set("gphoto2", "--set-config", "capturetarget=1");

**Comment by msmeissn** [comment]
capt0000.jpg is the SDRAM stored image, you need to download it immediately.

gp_setting_set("gphoto2", "--set-config", "capturetarget=1");  ... no, wrong syntax.

use something like
gp_setting_set("ptp2","capturetarget","card");


or edit ~/.gphoto/settings  directly and adjust the capturetarget line or add

ptp2=capturetarget=card

**Comment by SiuyuenChow** [comment]
> capt0000.jpg is the SDRAM stored image, you need to download it immediately.
> 
> gp_setting_set("gphoto2", "--set-config", "capturetarget=1"); ... no, wrong syntax.
> 
> use something like
> gp_setting_set("ptp2","capturetarget","card");
> 
> or edit ~/.gphoto/settings directly and adjust the capturetarget line or add
> 
> ptp2=capturetarget=card

To understand the
Cheers 🍻
Thank you very much
Best wishes,
Siu
