### ISSUE TITLE
Please support "Olympus Stylus XZ-10" for image capturing

### ISSUE THREAD

**Issue by markuszoeller** [gphoto/libgphoto2#68]
Olympus offers tethering software, but only for windows + macos (I use Linux). Using "wine" to work with the windows software doesn't successfully start the installation. Would be great to to have this in your library. Attached is my logfile. Thanks a lot in advance!

[my-logfile.txt](https://github.com/gphoto/libgphoto2/files/344974/my-logfile.txt)

**Comment by msmeissn** [comment]
does the software really tether over usb? hmm

**Comment by markuszoeller** [comment]
It doesn't state otherwise on its page http://support.olympus-imaging.com/ov3download/ 
I'll use another camera system now, no need to keep this ticket open.

**Comment by msmeissn** [comment]
The trace did not show any capture related or unknown opcodes. :/ without a usb trace or reverse engineering drivers or documentation hard to implement.
