### ISSUE TITLE
Resolution of --capture-movie is odd.

### ISSUE THREAD

**Issue by PugzAreCute** [gphoto/libgphoto2#709]
**Describe the bug**

Resolution of `gphoto2 --stdout --capture-movie` is 640x424, instead of full hd (Setting set on camera)

**Name the camera**
Nikon DSC D3200

**libgphoto2 and gphoto2 version**
gphoto2         2.5.20
libgphoto2      2.5.22
libgphoto2_port 0.12.0 

**To Reproduce**
Run command `gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video2`, open a software like OBS, the resolution is not FullHD. I have only tested it on a Nikon D3200 As of now.

Log : Currently too big, will send if requested

**Comment by msmeissn** [comment]
is gphoto2 --summary | grep d1ac 
showing anything?
I fear it might not, so the liveview size might not be controllable...


the d1ac property, is also available decoded as  "liveviewsize"  in libgphoto2 2.5.26 and newer.

**Comment by PugzAreCute** [comment]
```bash
pugzarecute@debinax:~$ gphoto2 --summary | grep d1ac
pugzarecute@debinax:~$ 
```
Nope, no output., but to be fair my camera is pretty old

**Comment by msmeissn** [comment]
i fear it wont be adjustable :/

**Comment by PugzAreCute** [comment]
Ah ok, i see, ill try to take a movie on the cam itself to see if it can do full hd by itself

**Comment by PugzAreCute** [comment]
Looks like it can by itself

**Comment by msmeissn** [comment]
yes, but just to be clear capturing a movie on camera (in h264) is different from --capture-movie , which just repeatedly captures the liveview jpeg frame ;)

**Comment by PugzAreCute** [comment]
Ahh, ok!

**Comment by PugzAreCute** [comment]
Any way i can get the H264 feed live or no?

**Comment by msmeissn** [comment]
i am afraid i have not seen any regular camera that can stream h264 direct.

**Comment by PugzAreCute** [comment]
Closing as it is a camera limitation

**Comment by Binklebonk** [comment]
> 

It's a non-libgphoto2 solution, but as the question was "**Any way** I can get...", I feel compelled to suggest you may be able to utilise the cameras HDMI output, connected to a USB capture device, which will typically be detected by OSX/Windows/Linux as a webcam.  I'm able to achieve true 1080p with this.  Higher may be possible depending on your camera and capture device.

I must caution, that in my testing (with Nikon D750), I can not simultaneously output HDMI from the camera (requires LiveView to be active), whilst controlling it via libgphoto2 / gphoto2, or even having USB connected to the camera.  It's an exclusively one or the other deal, it seems.
