### ISSUE TITLE
Canon EOS 750D capture-preview failure

### ISSUE THREAD

**Issue by marcelmatula** [gphoto/libgphoto2#71]
Hi
I have an issue with gphoto2 2.5.10 on Ubuntu 14.04 LTS
capture-image works fine but capture-preview not.

I see in log:
2.030556 ptp_usb_getresp [usb.c:438] (0): PTP_OC 0x9153 receiving resp failed: Camera Not Ready (0xa102)
2.032688 camera_capture_preview [library.c:2569](0): get_viewfinder_image failed after all tries with ret: 0xa102

However it sometimes works but only when i run: gphoto2 --debug --capture-preview
It seems that debug option slowdown capturing which helps finish operation successfully.

See attached log.
I really need capture-preview feature - so let me know if you need any help in order to fix the issue.

Thanks,

Marcel
[my-logfile.txt](https://github.com/gphoto/libgphoto2/files/386756/my-logfile.txt)

**Comment by msmeissn** [comment]
can you try the attached commit (or current git)?

**Comment by marcelmatula** [comment]
Hi Marcus,

I tested latest development version 2.5.10.1 and it works perfectly for both capture-preview and capture-movie. Great job.

Thanks,
Marcel
