### ISSUE TITLE
Drop OS/2 support (appears to have been broken without complaints since 2006)

### ISSUE THREAD

**Issue by ndim** [gphoto/libgphoto2#710]
**Is your feature request related to a problem? Please describe.**
With Linux being the main target OS, *BSD a close second, and then MacOS, Window, and Android, libgphoto2 and gphoto2 are interesting enough to maintain for all those systems for which actual systems exist.

However, the following line has been in place for almost 15 years and it cannot have worked at any time since then:

```
9831fa553c libgphoto2_port/libgphoto2_port/gphoto2/gphoto2-port-portability.h (Hans Ulrich Niedermann 2006-10-06 18:41:05 +0000  77) #elif defined(__SOME_OS2_MAGIC_HERE__)
```

As I do not remember any complaints about lack of OS/2 support, I would conclude that there is a chronic lack of interest in libgphoto2 on OS/2.

**Describe the solution you'd like**
I would like to drop everything which is specifically related to OS/2.

**Describe alternatives you've considered**
Keep on needlessly worrying about how to be portable for a system which looks to not have been used for at least the last 15 years, and which has been broken for at least as long.

**Comment by msmeissn** [comment]
I am fine with removing it. have not heard of any os/2 user

**Comment by ndim** [comment]
@semanticfire Are you the Bart van Leeuwen mentioned as the maintainer of libgphoto2's OS/2 port in https://github.com/gphoto/libgphoto2/blob/master/MAINTAINERS? If so, is that port still maintained, or can we remove it?

**Comment by ndim** [comment]
After reading my commit message for 9831fa553c08988a32dc4226a2409ad76ccfec57, it appears that I have partly removed the OS/2 support back then in 2006, so removing the remainders has been overdue for more than a decade.
