### ISSUE TITLE
Inquiry func gp_widget_changed(widget) resets widget->changed flag to 0

### ISSUE THREAD

**Issue by Sija** [gphoto/libgphoto2#73]
Hi,

Is there any reason why inquiry function `gp_widget_changed(widget)` [modifies](https://github.com/gphoto/libgphoto2/blob/master/libgphoto2/gphoto2-widget.c#L829) passed `widget`? Typical use-case involves checking if given `widget` was changed and there's no indication that such call will modify the given `widget`.

``` c
gp_widget_changed(widget) // => true
gp_widget_changed(widget) // => false but expected true
```

**Comment by msmeissn** [comment]
this seems due to historic  reasons, was added during initial development of the library :(

**Comment by Sija** [comment]
I hope it's the time in history when we can move forward and str8 things up ;)

**Comment by Sija** [comment]
hi @msmeissn, could it be fixed for the next release?

**Comment by msmeissn** [comment]
(I did this now, but I wonder why you need it this way.)

**Comment by Sija** [comment]
@msmeissn Thanks!
