### ISSUE TITLE
Sony SLT-A77V (PTP mode) IO error

### ISSUE THREAD

**Issue by knro** [gphoto/libgphoto2#742]
Cannot capture. Is this camera officially supported? Using latest libgphoto2 from Git.

`gphoto2 --debug --debug-logfile=gphoto.txt --capture-image-and-download`

Camera: Sony SLT-A77V (PTP mode)

Bus 001 Device 009: ID 054c:0577 Sony Corp.

Debug log attached: [gphoto.txt](https://github.com/gphoto/libgphoto2/files/7519539/gphoto.txt)

**Comment by msmeissn** [comment]
i think it was released before sony started adding capture support.

does it support a "PC Control" option in its USB Menu on camera?

**Comment by jcustodio77** [comment]
It just shows USB Mass Storage and MTP Mode.

**Comment by msmeissn** [comment]
i am afraid there is not much we can do, sorry. It just does not support remote control.
