### ISSUE TITLE
Support for Sony Alpha7IIIA

### ISSUE THREAD

**Issue by tomsch1** [gphoto/libgphoto2#747]
**Name of the camera**
Sony Alpha 7 III A

**USB IDs**
`{"Sony:ILCE-7RM3A (PC Control)",		0x054c, 0x0d9b, PTP_CAP|PTP_CAP_PREVIEW}`

**Camera summary and config list**
Txt file with camera summary and config list is attached as a condensed file.
[sony-a7r3a.txt](https://github.com/gphoto/libgphoto2/files/7639825/sony-a7r3a.txt)

I actually added the USB IDs and the camera txt file already and created a Pull request, but it was deleted. Is it necessary to open a ticket for the pull request in the first place?

Anyways after adding the USB IDs, basic features work out of the box.

**Comment by msmeissn** [comment]
Hi,

the deleted pull request means it was merged into our master branch already, see commit 25d0eadafaf8f50e838dc762a6c2570812635874

Pull request is fine for us, or a regular ticket for future cameras.
