### ISSUE TITLE
Using libgphoto

### ISSUE THREAD

**Issue by 19hours** [gphoto/libgphoto2#752]
Hi everyone,

I know this is a c library, but I am not familiar with this. Can I just call the c functions by dragging the files into xcode? Or must I compile it first before I am able to use it in an ios project?

Many thanks

**Comment by ndim** [comment]
Off the top of my head, you may run into the following:

  * The instructions for building ´libexif` for iOS using Xcode @Joride has written in https://github.com/libexif/libexif/issues/82 can probably be helpful.
  * Do prerequisite libraries like `libusb*` (and optionally `libexif`) exist for and work on iOS? At least for `libexif`, things appear to work, according to https://github.com/libexif/libexif/issues/82.
  * Even if building works for iOS, do `libgphoto2` and `libgphoto2_port` work on iOS at all? Two possibly problematic areas coming to mind is
      * loading the camlibs and the iolibs
      * how does iOS handle USB devices and permissions, and do `libgphoto2`, `libgphoto2_port`, and the `iolib` implement that?
    This might already be implemented, but I am not familiar with it.
 
As a general remark, libgphoto2 was originally written to run on GNU/Linux, then ported to *BSD in the early 2000s. I tried some basic buildsystem type work for a Windows port in the mid 2000s out of curiosity. However, work porting to and actually making libgphoto2 work on more exotic operating systems like OSX, Windows, Android has picked up recently, but off the top of my head, I cannot remember about iOS.
