### ISSUE TITLE
Unable to get widget liveviewafmode (0xD05D) on Nikon D800

### ISSUE THREAD

**Issue by rlamarche** [gphoto/libgphoto2#78]
Hi,

I'm unable to get the widget liveviewafmode (0xD05D) on Nikon D800.
The point that I don't understand is that the 0xD05D code is listed with `gphoto2 --list-all-config` and I can set values through the widget name "d05d" but "liveviewafmode" is not accessible (so I don't get the labels).

Here my "--list-all-config" :

[d800.txt](https://github.com/gphoto/libgphoto2/files/429030/d800.txt)

**Comment by msmeissn** [comment]
can you also attach 
gphoto2 --summary

we might have a mismatch on the data type of the value

**Comment by msmeissn** [comment]
can you also run

gphoto2 --debug --debug-logfile=xx.log --list-all-config  and attach xx.log? it will probably contain errors on d05d

**Comment by rlamarche** [comment]
Ok

[summary.txt](https://github.com/gphoto/libgphoto2/files/429035/summary.txt)

[debug.txt](https://github.com/gphoto/libgphoto2/files/429036/debug.txt)

**Comment by rlamarche** [comment]
The most weird thing is that gp_camera_get_single_config is returning GP_OK but my widget is set to 0x0.

**Comment by msmeissn** [comment]
can you test this commit 96896d957381cc58afbe28d1193b27bfae07d819

**Comment by rlamarche** [comment]
![capture](https://cloud.githubusercontent.com/assets/379707/17839407/1ca9acc4-67e7-11e6-9d94-bf5ec9502f53.png)
