### ISSUE TITLE
Trigger capture while a file is downloading.

### ISSUE THREAD

**Issue by bkapadia02** [gphoto/libgphoto2#785]
I am writing an application where it is critical that I trigger the capture at the exact moment when a condition is met. It seems that there is no way to trigger a capture while a file is being sent from the camera to the PC. Is there a workaround for this other than having my main process to somehow kill the thread that is downloading the files?

**Comment by msmeissn** [comment]
The communication is pretty much over one pipe, the USB bus... interleaving commands / data like this is not really possible.

if the main process is downloading in smaller blocks as we do with getpartialobject these days, you can inject commands inbetween.

**Comment by msmeissn** [comment]
no further comms received, please reopen if needed
