### ISSUE TITLE
Travis CI builds are failing on Mac OS

### ISSUE THREAD

**Issue by Sija** [gphoto/libgphoto2#79]
Seems like it's due to lack of `libtool` (as described in https://github.com/maxmind/libmaxminddb/issues/9) which, oddly enough is uninstalled [here](https://github.com/gphoto/libgphoto2/blob/master/.travis.yml#L16), hence the error :)

**Comment by msmeissn** [comment]
i know. previously it was not working,. I will try to remove the uninstall again

**Comment by msmeissn** [comment]
i removed the uninstall libtool line and it succeeds now.

**Comment by Sija** [comment]
Green is good, thanks! ;>
