### ISSUE TITLE
Does ```gp_widget_add_choice()``` function works?

### ISSUE THREAD

**Issue by d3lure** [gphoto/libgphoto2#802]
### Problem description
I'm currently trying to set Nikon Coolpix P1000 focal length (which is up to 105mm only in config, in reality it is 3000mm). And after reading some documentation I found out that there is a function to add choice in MENU widgets, but it doesn't change camera's config / it doesn't save added choice unfortunately. 

```python
camera = gp.check_result(gp.gp_camera_new())
gp.check_result(gp.gp_camera_init(camera))
config = gp.check_result(gp.gp_camera_get_config(camera))

fl = config.get_child_by_name('5008')
print(gp.gp_widget_count_choices(fl))
gp.gp_widget_add_choice(fl, "2400")
print(fl.get_choice(7))
print(gp.gp_widget_count_choices(fl))

gp.gp_camera_set_config(camera, config)
gp.check_result(gp.gp_camera_exit(camera))
```

It prints the following:
>7
2400
8

Which is fine, but it prints this result no matter how many times I run the program.

**Comment by d3lure** [comment]
Okay, so if I understand correctly, there is no way I can go beyond the focal length values that are given in gphoto2?

**Comment by msmeissn** [comment]
We retrieve and use the values the camera offers to use here.

can you quote:
gphoto2 --summary | grep 5008


You can always try sending values outside of these choices to the camera and see what happens.

The generic property code setter for 0x5008 is not validating the values against the choices, it will send to the camera whatever you try to set.

**Comment by d3lure** [comment]
Unfortunately I don't have camera nearby at the moment, but as far as I remember trying to set values outside the range using commandline ```gphoto2 --set-value 5008=2400``` resulted in error.

**Comment by d3lure** [comment]
> 

After ```gphoto2 --summary | grep 5008``` I got:
Focal Length(0x5008):(readwrite) (type=0x6) Enumeration [3500,4600,5300,6100,7300,8600,10500] value: 35 mm (3500)

And if I try to set value ```gphoto2 --set-config 5008=12500``` which is not in enum I get the following error:

*** Error ***              
The property 'Focal Length' / 0x5008 was not set (0x201c: PTP Invalid Device Prop Value).

**Comment by msmeissn** [comment]
i am afraid this is what the camera reports to us... it does not accept this value. 
there is sadly not much we can do on libgphoto2 side.
