### ISSUE TITLE
Canon EOS 1500D and 2000D are the same 

### ISSUE THREAD

**Issue by manongjohn** [gphoto/libgphoto2#812]
Hi.

I have a Canon EOS 2000D but it comes up as 1500D because it has the same `usb_product` code as the 2000D shown here:

https://github.com/gphoto/libgphoto2/blob/c7cce560c139e71e5d9e530b0792c7a2979f3316/camlibs/ptp2/library.c#L2453-L2457

According to Wikipedia

> The Canon EOS 2000D, known as the Rebel T7 in the Americas, as the Kiss X90 in Japan and as the 1500D in southeast Asia, ...

I'm wondering if these entries should really be merged since they are apparently the same camera with different names but have slightly different `device_flags`?

**Comment by msmeissn** [comment]
i merged the flags,t hanks for the notice!
