### ISSUE TITLE
Nikon D7500 trigger start/stop remote video capture

### ISSUE THREAD

**Issue by JakubSpy** [gphoto/libgphoto2#818]
I'm trying to remotely capture video from my Nikon DSLR, using this command 'gphoto2 --set-config movie=1 --wait-event=10s --set-config movie=0 --wait-event-and-download=5s' I am able to capture video footage for the duration of 10s using the above command however ideally for the project im developing I require a trigger system where before I don't know how long the capture is going to be. 

This would be a start/stop recording system where remotely I can tell the camera to start recording and then stop at a time when a trigger (such as a button) is used to stop the video with no predetermined recording time. Is this possible with gphoto?

I have tried to set the capture time to near infinite and then press ctrl-c or ctrl-z to stop the recording, however when I do that the video is not downloaded and I receive no video file.

Any help would be greatly appreciated!

**Comment by msmeissn** [comment]
see other ticket in gphoto2 space.
you can of course always write a libgphoto2 using program in C, or python for instance that handles specific logic outside of gphoto2 commandline tool abilities.
