### ISSUE TITLE
Support for Fujifilm X30 (if possible)

### ISSUE THREAD

**Issue by heinrichWeichert** [gphoto/libgphoto2#825]
Would it be possible to add support for capture for the mentioned camera?
I could assist in giving debug logs etc. as I own this camera of course.

**Comment by msmeissn** [comment]
see also https://github.com/gphoto/libgphoto2/issues/281

It is likely not supporting remote control. Is there any FUJI documentation saying it should support remote control?

If you have it, can you try

gphoto2 --summary
gphoto2 --capture-image-and-download

?

**Comment by heinrichWeichert** [comment]
I'll try the commands, thx
