### ISSUE TITLE
Canon EOS R6 Mark II support

### ISSUE THREAD

**Issue by ecidiego** [gphoto/libgphoto2#881]
**USB ID:**

04a9:330b

**Marketing name:**

Canon EOS R6 Mark II

**summary.txt:**

[summary.txt](https://github.com/gphoto/libgphoto2/files/10271151/summary.txt)

**list-all-config.txt:**

[list-all-config.txt](https://github.com/gphoto/libgphoto2/files/10271156/list-all-config.txt)

**capture preview DOES work, attaching file in case you need it:**

**capture and download created and saved a cr3, but it's a small ( 1.54MB ) blank pic.**

![capture_preview](https://user-images.githubusercontent.com/121066007/208739928-80b42d71-19c4-4e19-984b-a2c0e4a3ea9f.jpg)

![capture-screenshot](https://user-images.githubusercontent.com/121066007/208775799-5de54948-f9d2-44d6-8703-5df3e143aff4.jpg)

**Comment by msmeissn** [comment]
we need the above information to add it ... at least the USB ids. :)

**Comment by ecidiego** [comment]
> we need the above information to add it ... at least the USB ids. :)

I'll have this today. Really hoping you guys can squeeze it in. Where can I donate? I see you will be adding EOS R7 and R10 - gotta get R6 Mark II in the next release! Thanks so much for this project.

**Comment by ecidiego** [comment]
> we need the above information to add it ... at least the USB ids. :)

**USB ID:**

04a9:330B

**Marketing name:**

Canon EOS R6 Mark II

**summary.txt:**

[summary.txt](https://github.com/gphoto/libgphoto2/files/10271151/summary.txt)

**list-all-config.txt:**

[list-all-config.txt](https://github.com/gphoto/libgphoto2/files/10271156/list-all-config.txt)

**capture DOES work, attaching files in case you need them:**

![capture_preview](https://user-images.githubusercontent.com/121066007/208739928-80b42d71-19c4-4e19-984b-a2c0e4a3ea9f.jpg)

Thank you so much, again, for this project!

**Comment by msmeissn** [comment]
if you want to donate money: http://gphoto.org/doc/donate.php

But already that you help testing cameras is a great contribution!

If you are able to, can you build libgphoto2 master, and try 

gphoto2 --set-config testolc=1 --debug --debug-logfile=olc-debug.log 
and attach olc-debug.log ?

**Comment by ecidiego** [comment]
I got:

*** Error ***
testolc not found in configuration tree.
*** Error (-1: 'Unspecified error') ***

I did download and build off the Master

**Comment by msmeissn** [comment]
(sorry for late reply)
what does gphoto2 --version   report? if it does not say 2.5.30.1 libgphoto2 it probably still using the system libs

**Comment by ecidiego** [comment]
>
>
> Any guestimates if an R6 Mark II supporting build is on the way?
>

From the App dev I am trying to use it with...

[image: image.png]

**Comment by givoly** [comment]
Will you be adding support for the R6M2 as well as R7/R10 soon?

**Comment by msmeissn** [comment]
The image did not go through, sorry.

gphoto2 --version should show 
libgphoto2 2.5.30.1 

for other EOS cameras, please report them via separate tickets. As written here, they likely will work already, we just need some small adjustments, and the USB ids for correct name reporting.

**Comment by ecidiego** [comment]
Any idea when gphoto2 will be updated? The vendor I want to use my R6 Mkii with won't budge... they say "when gphoto2 updates we will update. "

**Comment by msmeissn** [comment]
i am planning to cut a new release in the next weeks, life is just super busy the last year for me.

**Comment by axxel** [comment]
libgphoto2-2.5.31 is released and includes the R6 Mark II support, right?

**Comment by msmeissn** [comment]
yes
