### ISSUE TITLE
Modern Pentax Cameras not supported, possibly due to outdated PKRemote library, not PKTriggerCord library

### ISSUE THREAD

**Issue by ian-morgan99** [gphoto/libgphoto2#928]
I am working with two solutions, which are both seeming dependent on LibGphoto2. 

One is 'Astroberry' which uses Indilib which uses LibGphoto2.
The other is Benro Polaris which as far as I understand, is also using a similar approach.

Neither of these solutions recognise modern Pentax cameras, such as the Pentax K3iii.
These solutions both fail to be able to use the LiveView feature of the Pentax K1ii.

As far as I can see, the Gphoto library is based on an old PKRemote project, which doesn't appear to be actively updated, and is missing features of a number of newer Pentax models. I believe this is why the K3iii for example, is completely unsupported.

There is a newer project, PKTriggerCord (https://github.com/asalamon74/pktriggercord) which appears to have support for new camera models, such as the Pentax K3iii and Pentax K1ii.

I have only attempted to connect using these compiled solutions, so have not been able to test in a way that allows me to generate the following:

**Name the camera**
Camera name as shown by gphoto2 --auto-detect or USB IDs
**libgphoto2 and gphoto2 version**
output of: gphoto2 --version
**To Reproduce**
When reproducing with the commandline tool, attach debugout using  --debug --debug-logfile=debug.log   if considered useful.

I will attempt to do so. In the mean time, could you consider upgrading the solution to use the newer Pentax PKTriggerCord library?

**Comment by msmeissn** [comment]
we also need the USB ids of the K-1 II

**Comment by msmeissn** [comment]
commit 3118a779151d9b39b907a2b2817929011b0a9bd3

again, we still need the USB ids of the K3-III and K1-II

**Comment by ian-morgan99** [comment]
I will see how I can find that out. I have both cameras here .

**Comment by msmeissn** [comment]
run

lsusb

with the camera attached

**Comment by msmeissn** [comment]
see pktriggercord issue. ids added to current libgphoto2 GIT.

(the ids are largely used for detection purposes)

**Comment by ian-morgan99** [comment]
Many thanks for your quick response on this 👍 

As I'm new to this world, how does this update find it's way into the downstream projects that use it?
Should I now go chase IndiLib , Astroberry and the folks at Benro who are using this library, to get them to update from it, or are there other steps that need to happen first?

Sorry for the newbie questions

**Comment by msmeissn** [comment]
i put fixes in libgphoto2. the next release is still some time out, as i just did a release some weeks ago.
as soon as its out, indi and others pick it up usually.

perhaps they even do git snapshots, not sure. you would need to ask them

**Comment by ian-morgan99** [comment]
Many thanks.

**Comment by msmeissn** [comment]
closing

**Comment by ian-morgan99** [comment]
It appears that the initial issue is not resolved , because of other problems in the PKtriggercord library . The Pentax K1ii and Kiii are not working when used directly , so fixing the issue downstream didn't resolve the issue . I will raise a fresh issue once I can see how that could possible be addressed .

**Comment by ian-morgan99** [comment]
I have returned to this, and am attempting to port my own implementation for newer Pentax cameras.
If there is anyone who has patience to support a beginner with this process. I would greatly appreciate your support.
