### ISSUE TITLE
Sony Alpha 6100 PC-control mode

### ISSUE THREAD

**Issue by kjetilk** [gphoto/libgphoto2#943]
**Name of the camera**

Sony Alpha 6100

In this issue, I have set it up in PC-control mode.

**USB IDs**

```
Bus 005 Device 024: ID 054c:0d14 Sony Corp. ILCE-6100
```

**camera summary output**

[summary.txt](https://github.com/gphoto/libgphoto2/files/13634406/summary.txt)

**camera configuration output**

[config.txt](https://github.com/gphoto/libgphoto2/files/13634426/config.txt)

**test capture**

*  gphoto2 --capture-image-and-download
 
Works!

*  gphoto2 --capture-preview

Works!

**Comment by msmeissn** [comment]
added id to git, thanks for the report!
